### ISSUE TITLE
[bug] "rate limit exceeded" for non-existent issues

### ISSUE THREAD

**Issue by fixator10** [upptime/upptime#100]
If you try to access issue that doesn't exists, you will get "Rate limit exceeded" message, but ratelimit is not exceeded.

https://demo.upptime.js.org/incident/9001

**Comment by AnandChowdhary** [comment]
It seems like it redirects all errors to this one. Let me fix it quickly!

**Comment by AnandChowdhary** [comment]
Done! 😄
