### ISSUE TITLE
graphs not updating

### ISSUE THREAD

**Issue by maximousblk** [upptime/upptime#106]
screenshot:

![image](https://user-images.githubusercontent.com/28438021/101135867-71c60680-3632-11eb-9e05-058c7710571c.png)

I believe this is caused by the change in directory structure of graphs but the readme was not updated for this change?

old: `/graphs/website.png`
new: `/graphs/website/response-time.png`

**Comment by maximousblk** [comment]
this does not seem like it was intended

![image](https://user-images.githubusercontent.com/28438021/101136392-442d8d00-3633-11eb-9876-7b4222a546d4.png)

![image](https://user-images.githubusercontent.com/28438021/101136575-8b1b8280-3633-11eb-9b50-7faa4700d7da.png)

**Comment by shirt-dev** [comment]
I'm having this issue as well.

**Comment by AnandChowdhary** [comment]
This has been fixed. 😄
