### ISSUE TITLE
ICMP Monitoring

### ISSUE THREAD

**Issue by SagnikSRHUSE** [upptime/upptime#111]
I was wondering if it's possible to monitor ICMP response times, instead of HTTP response times. Also, would it be possible to disable showing the response times altogether?

**Comment by RafGamer** [comment]
Maybe it's also possible to add even more protocols.🤔

**Comment by AnandChowdhary** [comment]
Let's track this in #73. As of now, unfortunately there's no way to monitor anything other than the HTTP response time, but this is something I'd be happy to explore.

**Comment by alvarolopez** [comment]
:+1: to this, ICMP would be extremely useful.

**Comment by aweiand** [comment]
As you implemented tcp-ping , why can`t implemented [node-icmp](https://github.com/QuantumSheep/node-icmp) where has a real icmp functionality? 
The tcp-ping it`s fine, but continues as http/https, which unattended some servers and infrastructures...
