### ISSUE TITLE
Incorrect issue in link in docs

### ISSUE THREAD

**Issue by AryanBeezadhur** [upptime/upptime#113]
In the docs, [at the bottom of the paragraph below this header](https://upptime.js.org/docs/#github-actions-powered-uptime-monitor), there is a link to an example issue for a broken site, #15, but it has now been deleted.

The correct example issue is #67.

**Comment by AnandChowdhary** [comment]
Awesome! Can you make a PR to correct this?

**Comment by AryanBeezadhur** [comment]
Closed by https://github.com/upptime/upptime.js.org/pull/10
