### ISSUE TITLE
Is it correct to set notifications like this?

### ISSUE THREAD

**Issue by belhyun** [upptime/upptime#120]
I added the following to the repository token to set up email notification. Is there anything else I need to set up? Also, if you want to send an email to multiple people, can you set NOTIFICATION_EMAIL_TO to connect the email with,?

![image](https://user-images.githubusercontent.com/895026/102303309-40d4c280-3f9e-11eb-845e-8cf959d59cb2.png)

**Comment by AnandChowdhary** [comment]
This is correct, yes. Can you confirm if the emails are **not** going?
