### ISSUE TITLE
Support to group endpoints into services

### ISSUE THREAD

**Issue by alvarolopez** [upptime/upptime#121]
For complex setups, it would be desirable to have a way to group different endpoints into higher level services).

For instance, one could have a group "Webservers" with several endpoints, and another group "Database" with other endpoints, and so on and so forth. It should also be possible to generate downtimes, issues and interventions also to these services.

**Comment by AnandChowdhary** [comment]
Makes a lot of sense, yes! How do you envision this working? Say you add 3 sites to a "group", we will not only tell you the response time etc. of each site, but also a group average? And perhaps a collapsable in the README?
