### ISSUE TITLE
Not able to assign issues, 422 from GitHub

### ISSUE THREAD

**Issue by MridulS** [upptime/upptime#125]
**Describe the bug**

To able to assign issue to a GitHub user automatically whenever a degradation/downtime occurs.

**To Reproduce**

config file -> https://github.com/gesisnotebooks/status/blob/c9e624b1d2709dc774f9aa0b1a8b6b0e07b338e0/.upptimerc.yml

Github Action run -> https://github.com/gesisnotebooks/status/runs/1576330978

**Expected behavior**
The issue should be assigned to the users in assignees.

**Screenshots**

From "update response time" step 
```
ERROR RequestError [HttpError]: Validation Failed: {"value":"MridulS","resource":"Issue","field":"assignees","code":"invalid"}
```

**Comment by AnandChowdhary** [comment]
I just noticed that the GitHub docs say "This field is deprecated": https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#create-an-issue--parameters

Maybe that's the problem which wasn't there, let me have a closer look!

**Comment by AnandChowdhary** [comment]
This is now fixed, we add assignees using the new API rather than while creating the event. Note, however, that only uses with push access (i.e., your personal access token needs push access, which it likely does) can assign users to an issue.

**Comment by MridulS** [comment]
Thanks @AnandChowdhary !
