### ISSUE TITLE
HTTP 301 check fails if original page redirects to a page that returns HTTP 200

### ISSUE THREAD

**Issue by flother** [upptime/upptime#127]
**Describe the bug**

If you set an endpoint's expected status code to 301, Upptime will flag the endpoint as down if the page the endpoint redirects to returns HTTP 200.

**To reproduce**

Steps to reproduce the behaviour:

1. Track a website that a) returns HTTP 301, b) its redirect returns HTTP 200, and c) tell Upptime to look for an HTTP 301 response
   
   ```yaml
   sites:
   - name: North Atlantic Radio
     url: https://www.northatlanticradio.com
     expectedStatusCodes:
       - 301
   ```

2. Commit and push the change

3. Wait for the action to complete and a "down" issue to be created

I'm running [this config in flother/upptime](https://github.com/flother/upptime/blob/c4f3c6434453a764c2c07537c069871e091b4d32/.upptimerc.yml#L10-L14). Here's the [resulting issue](https://github.com/flother/upptime/issues/1). The website it's checking is up:

```sh
$ curl -v https://www.northatlanticradio.com
*   Trying 134.209.226.211...
* TCP_NODELAY set
* Connected to www.northatlanticradio.com (134.209.226.211) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.northatlanticradio.com
*  start date: Dec 11 06:02:41 2020 GMT
*  expire date: Mar 11 06:02:41 2021 GMT
*  subjectAltName: host "www.northatlanticradio.com" matched cert's "*.northatlanticradio.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fab4100e800)
> GET / HTTP/2
> Host: www.northatlanticradio.com
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
> Accept: */*
> Referer:
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 150)!
< HTTP/2 301
< content-length: 47
< content-security-policy: default-src 'self'; form-action 'self'; frame-ancestors 'none'; block-all-mixed-content; upgrade-insecure-requests;
< content-type: text/plain; charset=utf-8
< date: Sat, 19 Dec 2020 13:51:50 GMT
< location: https://www.flother.is/podcast/
< strict-transport-security: max-age=63072000; includeSubDomains
< x-content-type-options: nosniff
< x-frame-options: 1; mode=block
< x-xss-protection: DENY
< age: 1666
< server: Netlify
< cache-control: max-age=86400,must-revalidate
< x-nf-request-id: 784e59b6-6a77-45f0-ae97-52cfee40949c-5859217
<
Redirecting to https://www.flother.is/podcast/
* Connection #0 to host www.northatlanticradio.com left intact
* Closing connection 0
```

**Expected behaviour**

When Upptime receives an HTTP 3xx response, it shouldn't follow the redirects if a 3xx code is included in the [`expectedStatusCodes` config](https://upptime.js.org/docs/configuration#status-codes).

It might also be useful to have a setting per endpoint to configure whether redirects should be followed.

**Comment by AnandChowdhary** [comment]
This is interesting, I wouldn't have thought that node-libcurl follows redirects by default (since curl doesn't). In https://github.com/JCMais/node-libcurl/issues/69#issuecomment-253623203, it looks like we can set `MAXREDIRS` to `0` to prevent it from following redirects, so I'll set that up!

**Comment by AnandChowdhary** [comment]
This is now added, you can add the maximum number of redirects you'd like to follow:

```yaml
sites:
  url: https://example.com
  name: Example
  maxRedirects: 10
```

In the above example, up to 10 redirects will be followed. By default, 3 redirects are followed. In your case, setting this to 0 should prevent curl from following any redirects.

**Comment by flother** [comment]
Thanks for looking into this so quickly, I appreciate it.

I added `maxRedirects: 0` in flother/upptime@bcab9022b79c0c0a3a55148638030f72ee8e8d1b and updated to v1.23.12 of uptime-monitor in flother/upptime@65086f7fa6f5b4c3c5eeb8c7c3cc919207ce5415 (by [manually triggering the Update Template CI action](https://github.com/flother/upptime/actions/runs/434214824)). But the Uptime CI job is still flagging the site as down (see [this recent run](https://github.com/flother/upptime/runs/1588491158?check_suite_focus=true#step:3:15)). Either I'm doing something wrong (always possible) or Upptime isn't yet limiting the redirects.

**Comment by rcdailey** [comment]
I don't think the implementation I'm seeing is sufficient:

```js
curl.setOpt("MAXREDIRS", site.maxRedirects || 3);
```

If I set `maxRedirects` to 0, it still allows redirects. I believe this is because the expression `0 || 3` yields `3`. I think the logic needs to account for "null" and only set it to 3 if that's the case, 0 is still valid and should be chosen. I'm not a Javascript wizard so I don't know what the exact code should be

**Comment by cterrasid** [comment]
Hi! I've been experiencing the same issue described [here](https://github.com/upptime/upptime/issues/127#issue-771390495).

According to the solution, I've setted the `maxRedirects` to `0`, but it doesn't solve the problem, because now, the status is `0` and not the expected `301`, as you can see in the image: <img width="1386" alt="Screenshot 2021-11-15 at 13 00 38" src="https://user-images.githubusercontent.com/48140509/141778597-2bc8e3b1-4a59-4859-bd6e-e15325f4e922.png">

What can I do in this case?

**Comment by vjrj** [comment]
Worked for me after removing the `expectedStatusCode` and following https://github.com/upptime/upptime/issues/127#issuecomment-748592190
see my change:
https://github.com/GBIFes/status/commit/8e8e76947ea4328b201046a3f800b4936ebb57f7
