### ISSUE TITLE
Notifications (Slack & SMTP) aren't working

### ISSUE THREAD

**Issue by SelrahcD** [upptime/upptime#132]
Hi 👋, thanks for the great project!

**Describe the bug**
Notifications aren't working. I've probably messed up something as I'm apparently the only one having trouble.

I've set up both Slack and SMTP via the GitHub secrets as [described on the documentation](https://upptime.js.org/docs/notifications/). None of them are working so far.

SMTP is Gmail one, I've followed instruction from [their help page](https://support.google.com/mail/answer/7126229?hl=fr).

I've tried sending me a notification using Curl for Slack and it worked.

[Action logs](https://github.com/SelrahcD/uptime/runs/1601631569?check_suite_focus=true) are saying that the notification was sent

> Sending notification 🟩 Schtroumpsify (http://schtroumpsify.chorip.am/) is back up.

**To Reproduce**
Well, you could try to set up notifications but it might work 😅

**Expected behavior**
I should have received an email and a Slack message.

**Screenshots**
<img width="913" alt="Capture d’écran 2020-12-23 à 18 56 00" src="https://user-images.githubusercontent.com/1864786/103024688-a140a280-4550-11eb-89d2-568333d5d4ef.png">

**Desktop (please complete the following information):**
Not relevant

**Smartphone (please complete the following information):**
Not relevant

**Additional context**
Let me know if I can provide some more details or if it's easier for you if I split the issue in two, one for SMTP and one for Slack.
Is it possible to turn logging on?
Again, thanks for that project, it's a really clever idea to use GitHub actions for this 💡

**Comment by SelrahcD** [comment]
Hi Anand,

Github marks that assigned you to the issue. Sorry for that; it's probably a misclick...

I've investigated a little the past week and wanted to share what I've seen if it can help.

I managed to display logs using the `ACTIONS_STEP_DEBUG` env var, setting it to `true.` Unfortunately, no logs are printed around the notification code.

I dug into the [Uptime-monitor](https://github.com/upptime/uptime-monitor) repo and noticed there were two notifications system, [Notifications](https://github.com/upptime/uptime-monitor/blob/master/src/helpers/notifications.ts) and [NotifyMe](https://github.com/upptime/uptime-monitor/blob/master/src/helpers/notifme.ts).

Looking at the repo and past changes, I believe the first one is no longer in use, and NotifyMe is currently used. This is where I stopped as I didn't take the time to look at how I could provide my own version of the uptime-monitor code to add some logs. Let me know if you think giving a closer look can help.

Enjoy the holiday season.

**Comment by janik6n** [comment]
Just to add another user, I have not been able to get Slack notifications to work either. All the configuration is correct according to documentation, and the Slack webhook works when tested from elsewhere.

**Comment by endofhome** [comment]
I don't want to hijack the thread but I am wondering if this might be an issue with notifications more generally - I haven't been able to send email notifications via Sendgrid but I can send email outside of Upptime using the same configuration.

**Comment by AnandChowdhary** [comment]
I'll have a closer look this week! 😄

**Comment by esirK** [comment]
Thanks for the good work @AnandChowdhary 
Just adding that I'm also having the same issue with slack.

**Comment by pkyeck** [comment]
Any updates on this?
I appreciate all the work you all put into this project - but notifications is one of the biggest must-haves for uptime monitoring. Fancy status-pages are nice but who is checking them every 5mins ... I want to be notified when something is wrong. So please make notifications work ❤️

**Comment by varadiz** [comment]
Seems like `process.env` is not read properly in `helpers/notifme.ts`.

I added this to `workflows/uptime.yml` as a test and got a slack notification.
NOTE: `uptime.yml` gets updated daily, so this is not a solution or workaround in any form.

```
env:
          GH_PAT: ${{ secrets.GH_PAT }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          NOTIFICATION_SLACK: ${{ secrets.NOTIFICATION_SLACK }} 
          NOTIFICATION_SLACK_WEBHOOK: ${{ secrets.NOTIFICATION_SLACK_WEBHOOK }} 
          NOTIFICATION_SLACK_WEBHOOK_URL: ${{ secrets.NOTIFICATION_SLACK_WEBHOOK_URL }}
```

I can see that uptime.yml  reads all secrets and stores in an env var called `SECRETS_CONTEXT`. 
I can also see that `helpers/environment.ts` does "something" to the env variables. 
Most probably the bug is somewhere here. 

Thank you for the great tool!

**Comment by debdutdeb** [comment]
> I don't want to hijack the thread but I am wondering if this might be an issue with notifications more generally - I haven't been able to send email notifications via Sendgrid but I can send email outside of Upptime using the same configuration.

Same with me. No SendGrid or SMTP.

**Comment by flaxton** [comment]
I use SendGrid on many projects/systems, but it isn't working for me on upptime.

**Comment by debdutdeb** [comment]
Those who want email notifications, a temporary workaround - https://github.com/debdutdeb/upptime-email-notify

This does defeat the purpose of the "no server needed" part, but for now if you can, this will help.

**Comment by AnandChowdhary** [comment]
This is now (finally) fixed, thanks so much for your patience! The fix is available in [`upptime/uptime-monitor@v1.26.2`](https://github.com/upptime/uptime-monitor/releases/tag/v1.26.2), and the automated fix should be in your repositories within 24 hours.

You can also run Update Template CI [manually](https://upptime.js.org/docs/triggers) to update to the latest version immediately; by default this runs once every day.

**Comment by SelrahcD** [comment]
Nice, thank a lot @AnandChowdhary 
Can't wait to see my website going down to see how it's going 🙂

**Comment by aweiand** [comment]
Hi people,

It was working now? I'm have a setup with only SENDGRID and was not working... I was tested SMTP too, with gmail configuration, but seems to not working too....
