### ISSUE TITLE
Loading module from “https://triptoafsin.github.io/client/client.be35e405.js” was blocked because of a disallowed MIME type (“text/html”).

### ISSUE THREAD

**Issue by TriptoAfsin** [upptime/upptime#173]
**Describe the bug**
I followed all the necessary steps, but my github pages was stuck on the loading spinner, then i checked the console and saw this, any help would be appreciated 

**Screenshots**
https://i.imgur.com/vbxuADf.png

**Comment by AnandChowdhary** [comment]
Please see https://upptime.js.org/docs/faq. You haven't added the base URL to your configuration.
