### ISSUE TITLE
`Update Summary in README` workflow failing

### ISSUE THREAD

**Issue by forstermatth** [upptime/upptime#176]
**Describe the bug**

The `Update Summary in README` workflow is failing because of a dependency change. 

> Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.

Related to https://github.com/upptime/graphs/pull/57

**To Reproduce**
1. Run the workflow

**Expected behavior**

The workflow passes with the correct change.

**Screenshots**

![Screen Shot 2021-01-05 at 11 32 36 AM](https://user-images.githubusercontent.com/3375444/103685016-b7cffc00-4f49-11eb-882b-a34776990117.png)

**Comment by forstermatth** [comment]
I ran into this when _adding_ a new endpoint, but afterward, it started running cleanly again.

**Comment by AnandChowdhary** [comment]
This is fixed in https://github.com/upptime/uptime-monitor/releases/tag/v1.24.2. 😄
