### ISSUE TITLE
Static GH site looks bad

### ISSUE THREAD

**Issue by Milo123459** [upptime/upptime#179]
Windows 10 Google chrome 87:
Example https://milo123459.github.io/upptime

**Comment by AnandChowdhary** [comment]
Please see https://upptime.js.org/docs/faq. You haven't added the base URL to your configuration.

**Comment by Milo123459** [comment]
@AnandChowdhary I did that and it still doesnt't appear to work. I re ran the setup CI as well. any ideas now?

**Comment by AnandChowdhary** [comment]
It looks good to me! :)

**Comment by Milo123459** [comment]
Yup, now it's fine, I have another question, how often does the GH workflow run fo rechecking uptime? It certainly isn't running every 5 minutes..

@AnandChowdhary
