### ISSUE TITLE
status-website: css value seems to be ignored

### ISSUE THREAD

**Issue by ConcurrentHashMap** [upptime/upptime#189]
Hey there,

there seems to be some sort of error, I cannot explain yet.

I put in the following line onto my .upptimerc.yml:

status-website:
  css: 'a.logo img { border-radius: 0 !important; height: 2rem !important; }'

This should be valid YAML.

Result:
The styling will not be added to my status page; although an empty <style> tag is present.

**Comment by AnandChowdhary** [comment]
This is pretty funny, it adds `<style>{config['status-website'].css}</style>` to your head. It seems like these variables aren't supported in `<script>` and `<style>` tags in Svelte. I'll fix this
