### ISSUE TITLE
Error: Input required and not supplied: token

### ISSUE THREAD

**Issue by gocreating** [upptime/upptime#190]
Github actions just shows `Error: Input required and not supplied: token`

**To Reproduce**
Just follow official docs `Create a repository from the template`
1. Create my own repo from the template repo
2. Clone my repo and update `.upptimerc.yml`
3. Push

**Screenshots**

![image](https://user-images.githubusercontent.com/5002343/104044255-061a1f00-5218-11eb-80d2-565ad6ce9939.png)

PS. I don't have any experience on github action. I just want to use upptime out of the box.

**Comment by AnandChowdhary** [comment]
Did you add the repository secret? https://upptime.js.org/docs/get-started#after-creating-your-repository

**Comment by gocreating** [comment]
Oh, I missed that part.
According to the docs, I can't find `Developer settings` or `Personal access tokens` in the settings sidebar
