### ISSUE TITLE
GitHub Pages error 404

### ISSUE THREAD

**Issue by Jamesking56** [upptime/upptime#192]
**Describe the bug**
I've for the first time just setup upptime and it says it has published a page, however, it is showing 404 error instead.

https://github.com/momentumstudioltd/status
https://momentumstudioltd.github.io/status/

**To Reproduce**
Steps to reproduce the behavior: Not sure

**Expected behavior**
Expecting to see the status site

**Comment by Jamesking56** [comment]
Turns out it was the branch protection rules I had added to the `gh-pages` branch stopping upptime from pushing to it.

Is there a way I can stop anyone from just pushing to `gh-pages` without stopping upptime?

**Comment by AnandChowdhary** [comment]
> Is there a way I can stop anyone from just pushing to gh-pages without stopping upptime?

Do you mean you don't want a status website at all, or do you want to prevent non-Uptime users from pushing to that branch?

**Comment by Jamesking56** [comment]
Prevent non-uptime users from pushing to `gh-pages`

**Comment by AnandChowdhary** [comment]
It seems like there is no way to do this using protected branches at this time: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuring-protected-branches

Maybe you can open a feature request with https://github.com/github/roadmap.

**Comment by tannerhallman** [comment]
@Jamesking56 Looks like you actually for this working. Can you share how you did that? I am running into the same issue.

**Comment by Jamesking56** [comment]
@tannerhallman https://github.com/upptime/upptime/issues/192#issuecomment-757362089

**Comment by EhsanHerai** [comment]
I have no protected branch. but my repo is private.
inside `index.html` is only text `404`

**Comment by AnandChowdhary** [comment]
[EhsanHerai](https://github.com/EhsanHerai) -> https://upptime.js.org/docs/faq/#my-status-website-doesnt-work-with-my-private-repository

**Comment by AnandChowdhary** [comment]
@EhsanHerai -> [My status website doesn't work with my private repository](https://upptime.js.org/docs/faq/#my-status-website-doesnt-work-with-my-private-repository)
