### ISSUE TITLE
gh_pages is cleared and replaced with only index.html, which contains 404

### ISSUE THREAD

**Issue by CoolCoderSJ** [upptime/upptime#205]
**Describe the bug**
I have followed all of the steps provided, all of my actions show status Passing, however the Github Pages is not working. The branch is cleared and replaced with index.html. Index.html contains one line, 404.

**To Reproduce**
1. Go to 'Settings > Secrets and add a new secret called GH_PAT with value as the Github PAT'
2. Click on 'Code tab, update .uptimerc.yml to put in your info'
3. Scroll down to 'README after a few minutes, it shows all badges as passing'
4. Go to the Github Pages provided, there is no css at first, then after a couple of minutes it shows 404

**Expected behavior**
The Github Pages looks like the one provided [here](https://demo.upptime.js.org)

**Screenshots**
![a](https://user-images.githubusercontent.com/53063247/104193182-d02e9380-53ed-11eb-9bdb-f7df98df89fb.PNG)
![b](https://user-images.githubusercontent.com/53063247/104193191-d1f85700-53ed-11eb-9438-4e163cb5351a.PNG)

**Desktop**
 - OS: Windows 7 64 bit
 - Browser: Firefox Developer Edition 
 - Version: 85.0

**Smartphone**
 - Device: OnePlus 3T
 - OS: OxygenOS 9.0.6
 - Browser Firefox Nightly 
 - Version 85.0

**Comment by CoolCoderSJ** [comment]
ah sorry apparently Private Repos dont work....Any reason why? It uses my PAT, so it should have access to the Repo

**Comment by AnandChowdhary** [comment]
Please see https://github.com/upptime/upptime/discussions/54 to use @upptime with a private repository.
