### ISSUE TITLE
Markdown code not formatting correctly on uptime website

### ISSUE THREAD

**Issue by soneji** [upptime/upptime#210]
**Describe the bug**
Markdown code not formatting correctly on uptime website. 

**To Reproduce**
1. Comment on issue with some code using  `````` triple backticks
2. Go to issue on website

**Expected behavior**
Code block in html

**Screenshots**
![image](https://user-images.githubusercontent.com/12625848/104452448-ecbbfe80-559a-11eb-8b9e-3ad58f226d46.png)

Issue in GitHub with proper code formatting: https://github.com/iskconpandavasena/uptime/issues/1
Issue on website without proper code formatting: https://uptime.psena.com/incident/1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 87.0

**Comment by AnandChowdhary** [comment]
We're currently using [developit/snarkdown](https://github.com/developit/snarkdown) on the frontend to parse markdown comments in issue, primarily because it's so small and I didn't want to include a huge markdown library on the frontend.

It seems from their example (http://jsfiddle.net/developit/828w6t1x/) that tripple-backtics are supported. Maybe you can see if changing the raw markdown to a similar syntax fixes the render?

**Comment by soneji** [comment]
I changed it to make it similar but it still appears to not work :( Maybe there is an issue with the API area downloading the data that removes the line breaks? That’s the only reason I can think it is not working

**Comment by soneji** [comment]
@AnandChowdhary I think it might be because inside my code block there are backticks. Should this issue be reported to the snarkdown library?

**Comment by AnandChowdhary** [comment]
> Should this issue be reported to the snarkdown library?

Yes, please! Feel free to refer to this issue to let them know!

**Comment by soneji** [comment]
I have reported this upstream. I will write back here if I get a response there.
https://github.com/developit/snarkdown/issues/96

**Comment by AnandChowdhary** [comment]
I'm closing this issue in favor of https://github.com/developit/snarkdown/issues/96. I ideally don't want to change the markdown parser because this is extremely lightweight for the frontend, so let's re-open this issue when we get a response and if there's anything we can do there.
