### ISSUE TITLE
I need help!!!!

### ISSUE THREAD

**Issue by navaneethkm004** [upptime/upptime#217]
Why my [status page](https://navaneethkm004.github.io/uptime/) is looking like that but the [demo](https://demo.upptime.js.org) is like that?

**Comment by navaneethkm004** [comment]
![image](https://user-images.githubusercontent.com/34748927/104808303-4c204580-580b-11eb-9a14-32f5aa29b6db.png)

**Comment by AnandChowdhary** [comment]
You didn't select gh-pages as the deployment branch: https://upptime.js.org/docs/get-started#enable-publishing

Please use discussions for Q&A.
