### ISSUE TITLE
The uptime cron interval of 5 minutes is not being fulfilled

### ISSUE THREAD

**Issue by r-chris** [upptime/upptime#224]
When looking at the action history of this repository: https://github.com/upptime/upptime/actions

You can see that the "Uptime CI" action only runs about once an hour and not once every 5 Minutes. The latest execution at this point in time was 31 minutes ago. Is this expected behaviour?

Related issue here: https://github.com/upptime/upptime/issues/42#issuecomment-765172955_

**Comment by r-chris** [comment]
<img width="885" alt="Screenshot 2021-01-22 at 07 43 15" src="https://user-images.githubusercontent.com/18341652/105456667-dc381200-5c85-11eb-884f-0cfa8384daf1.png">

**Comment by r-chris** [comment]
Ok - you already replied in #42 Thank you

**Comment by mathsen** [comment]
I don't know why this or [#42](https://github.com/upptime/upptime/issues/42) were both closed?
This is obviously a huge impact and should at least be noted in the manual or on the main site.
Yesterday I „installed“ upptime and wondered why „Uptime CI“ is running just every hour and here in this (closed) issue I find the answer.

If I need another server, that runs Jenkins, to overcome this issue (and even then depend on Github), this is a show breaker for me.

**Comment by AnandChowdhary** [comment]
> If I need another server, that runs Jenkins, to overcome this issue (and even then depend on Github), this is a show breaker for me.

I completely understand! Unfortunately, there's really not much we can do. Perhaps it's a good idea to open a ticket with GitHub about this?
