### ISSUE TITLE
Latest update completely broke my status page.

### ISSUE THREAD

**Issue by FxllenCode** [upptime/upptime#228]
**Describe the bug**
The latest update seems to have broken my entire site ever since I re-ran all workflows related to the update. It seems this happened when I tried to add the new dark theme, in which did not work, so I went back to normal, and it broke.

**To Reproduce**
1. Go to your upptime-power repository. 
2. Re-run Updates CI, Update CI, Setup CI, and Static-Site CI
3. Use the new dark theme and push.
4. Revert back to normal theme. (Dark theme is broken).
5. Site does not work.

**Expected behavior**
The site goes back to the normal light theme. 

**Screenshots**
![chrome_2Y8nsvCdXz](https://user-images.githubusercontent.com/40151425/105618361-3df69a00-5db4-11eb-9202-148ca6401959.png)

![7Y0Nt7Iduk](https://user-images.githubusercontent.com/40151425/105618365-43ec7b00-5db4-11eb-83fe-0dabdc08ee20.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser Chrome Canary
 - Version 90.0.4397.0

**Additional context**
View the site [here](https://status-plus.github.io/StatusPlus/).

The repository in question is [here](https://status-plus.github.io/StatusPlus/).

**Comment by AnandChowdhary** [comment]
Sorry, it seems like the URL to the theme was broken if you weren't using a custom domain. This is fixed in `v1.9.1`.
