### ISSUE TITLE
[v1.24.3] No custom domains

### ISSUE THREAD

**Issue by tarper24** [upptime/upptime#229]
**Describe the bug**
After @upptime updated itself to version 1.24.3, the `CNAME` file, and the `404.html`.
This error can be seen with the demo site from this repo itself.

**To Reproduce**
1. Go to '[Static Site CI #1711](https://github.com/upptime/upptime/runs/1759316098?check_suite_focus=true#step:5:23)'
2. Click on 'GitHub Pages Deploy'
3. Observe files not created.

**Expected behavior**
1. Go to '[Static Site CI #1710](https://github.com/upptime/upptime/runs/1755891519?check_suite_focus=true#step:5:23)'
2. Click on 'GitHub Pages Deploy'
3. Observe files are created.

**Screenshots**
![image](https://user-images.githubusercontent.com/3270079/105669299-9a38e700-5ea4-11eb-8b3e-a31af78fff37.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AnandChowdhary** [comment]
Aah, my bad! This is fixed and deployed! https://github.com/upptime/status-page/commit/811b6a486b575d8615a99d66d8a51d1bee2cc244

I missed the `await`, so [this condition](https://github.com/upptime/status-page/commit/811b6a486b575d8615a99d66d8a51d1bee2cc244#diff-6dbe8cf963f94ba9a0ff8ad1f035f54f56833f470201594e1f3802df17e2244fR26) was always `true` and it would throw an error while copying files, so it wouldn't continue with adding the CNAME and 404s.

Generating your site manually again ("Static Site CI") will fix this issue. The site will be regenerated automatically within 24 hours.
