### ISSUE TITLE
HTML Head Tags do not work

### ISSUE THREAD

**Issue by FxllenCode** [upptime/upptime#232]
**Describe the bug**
It seems that an error is thrown when using the new customHeadHtml. 

**To Reproduce**
1. Add any HTML tag using customHeadHtml.
2. Push your commit.
3. Almost instantly an error is thrown when building. 

**Expected behavior**
The page is built normally and the tags work. 

**Screenshots**
![104Gvxs8gU](https://user-images.githubusercontent.com/40151425/105786455-1e45aa00-5f4b-11eb-8258-0b242b779633.png)

![V4XKgLYeDh](https://user-images.githubusercontent.com/40151425/105786458-20a80400-5f4b-11eb-891e-87e29503e030.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome Canary
 - Version: 90.0.4397.0 (Official Build) canary (64-bit) (cohort: Clang-64)

**Comment by gerslun** [comment]
You might need to escape the quotes.

Example:
```yaml
customHtmlHead: "<meta charset=\"UTF-8\">"
```

**Comment by AnandChowdhary** [comment]
Yes, and you cannot have multiple items of the same key. You'd want to have one string that contains all the head tags, like:

```yaml
customHtmlHead: "<meta charset=\"UTF-8\"><another-tag />"
```

**Comment by AnandChowdhary** [comment]
Aah my bad, sorry!
