### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by fornever847** [upptime/upptime#234]
Is sick and hates and won't shut up
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AnandChowdhary** [comment]
You have to set `gh-pages` as the branch in your GitHub Pages settings: https://upptime.js.org/docs/get-started#enable-publishing
