### ISSUE TITLE
Graphs CI runs successfully but no graphs made.

### ISSUE THREAD

**Issue by RazerMoon** [upptime/upptime#236]
**Describe the bug**
The Graphs CI action gets a checkmark but doesn't actually produce any graphs.

**To Reproduce**
Not sure, you can check out my fork [here](https://github.com/RazerMoon/upptime). The gh-pages and response time seem to run fine. I just followed the instructions.

**Expected behavior**
The graphs get made.

**Screenshots**
![image](https://user-images.githubusercontent.com/33849459/106126168-f4f86a00-6154-11eb-868f-7b2f1542a322.png)
![image](https://user-images.githubusercontent.com/33849459/106126280-178a8300-6155-11eb-9e71-bfc7c09a392b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser: Chrome
 - Version: Newest Stable

**Comment by AnandChowdhary** [comment]
The API of the canvas render service we're using (`chartjs-node-canvas`) was changed. This has been fixed now.

**Comment by SmartBrave** [comment]
no graphs yet, please see: https://github.com/SmartBrave/uptime
