### ISSUE TITLE
Services that are up are marked as DOWN

### ISSUE THREAD

**Issue by williamdes** [upptime/upptime#243]
**Describe the bug**
All my endpoints are marked as DOWN, but they are UP..

**To Reproduce**
See: https://status.datacenters.network/

**Expected behavior**
Mark as UP

**Screenshots**
See: https://status.datacenters.network/

**Additional context**
Code: https://github.com/wdes/status

**Comment by kescherCode** [comment]
Nothing's marked as down anymore.

**Comment by williamdes** [comment]
> Nothing's marked as down anymore.

Oh yeah, thanks for the ping pong.
@AnandChowdhary said that it was because of my custom commit message not containing the up or down emoji

**Comment by williamdes** [comment]
Fix: https://github.com/wdes/status/commit/cfbf4d2079a50510fd3302013c93da1e97ddb677
