### ISSUE TITLE
The assets folder isn't being moved to gh-pages

### ISSUE THREAD

**Issue by flauc** [upptime/upptime#256]
**Describe the bug**
It looks like the contents of the assets folder (as described here https://upptime.js.org/docs/configuration#theme) isn't being moved in to gh-pages. 

**To Reproduce**
1. Add something to the `assets` folder
2. Look for it on the gh-pages branch

**Expected behavior**
The content of the assets folder would be there

**Screenshots**
![image](https://user-images.githubusercontent.com/4489834/107828170-93f1a880-6d88-11eb-9951-438aaaaaa7a7.png)

![image](https://user-images.githubusercontent.com/4489834/107828188-a0760100-6d88-11eb-92e2-49073e0e1a62.png)

**Additional context**
Looking at the code here https://github.com/upptime/uptime-monitor/blob/master/src/site.ts I don't see where this would be happening.

**Comment by bullwinkle** [comment]
same problem

**Comment by AnandChowdhary** [comment]
We do the copying here, not sure why it's not working! Let me debug: https://github.com/upptime/status-page/blob/master/post-process.ts#L25

**Comment by jamiew0w** [comment]
> 
> 
> We do the copying here, not sure why it's not working! Let me debug: https://github.com/upptime/status-page/blob/master/post-process.ts#L25

Hi @AnandChowdhary, just checking in to see if there's been progress made here. I don't mind if it takes another week or month, just wanna be sure I'm aware when it is fixed :)

**Comment by bullwinkle** [comment]
Looks like it works just in case you are building app from user/organization jekyll repo, but you still have to add /assets/ prefix. 
In case you are building Upptime from project repo, you can upload all static files like custom-theme.css to your user/organization repo and specify links in your Upptime repo, for ex `/assets/css/upptime-custom-theme.css`

**Comment by alistair3149** [comment]
Can confirm it is still an issue. Is there any updates on the progress?

**Comment by shabeer-ali-m** [comment]
same problem :(

**Comment by whoabuddy** [comment]
I am having the same problem, tried to create a custom css file but its inaccessible from the gh-pages branch.

**Comment by whoabuddy** [comment]
Hoping it could be something this simple, but not sure how to test this on my end, would definitely need some more time to dig.

In the `post-process.ts` file you linked, there is one `join` statement different from all of the others, it doesn't include the leading dot:

```javascript
await copy(join(".", "assets"), join("__sapper__", "export"), { recursive: true });
```
https://github.com/upptime/status-page/blob/54f5f60938f2c6ccdeabba224a540c0de9e8adf9/post-process.ts#L27

Should that be `join(".","__sapper__","export")` ?

Also, from what I see in my action logs for `Generate Site` this would be the line where the script is processed. Could adding some logging here provide output to the action? (i.e. "found assets folder", "copied contents", etc)

**Comment by fred-cardoso** [comment]
We are also not seeing the assets folder being moved to the GitHub pages as well.
I looked at the logs but there wasn't any clue on why this is happening.

**Comment by Nirmitjatana** [comment]
I faced the same issue and went through the discussion here. Seems like the fix mentioned here should work. Would like to raise a PR to close this issue. @AnandChowdhary

**Comment by bilalshaikh42** [comment]
Hi, is this released? I am still running into this bug from repo created today

**Comment by cdymlr** [comment]
Is this still not merged?

**Comment by ello-lithuania** [comment]
today same bug
