### ISSUE TITLE
ERROR Setup CI - Cannot read property 'commit' of undefined

### ISSUE THREAD

**Issue by volfclub** [upptime/upptime#262]
**Describe the bug**
Cannot read property 'commit' of undefined

**To Reproduce**
Setup CI 1 error
Cannot read property 'commit' of undefined

**Expected behavior**
when i run workflow

**Screenshots**
![image](https://user-images.githubusercontent.com/47265026/107967806-8dfa0280-6fe8-11eb-819b-b533aa1e678a.png)

![image](https://user-images.githubusercontent.com/47265026/107967613-4d01ee00-6fe8-11eb-920a-f986910e957a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AnandChowdhary** [comment]
Can you share the link to your repository?

**Comment by rimiti** [comment]
Same issue for us: https://github.com/tictactrip/upptime

**Comment by rimiti** [comment]
Same issue for us: https://github.com/tictactrip/upptime/runs/2012835496

**Comment by volfclub** [comment]
> 
> 
> Can you share the link to your repository?

https://github.com/volfclub/travellings-status

**Comment by rimiti** [comment]
My issue was related to a missing permission on the Github accesToken given.

**Comment by andrewsouthard** [comment]
I was able to fix this issue by running the `Response Time CI` workflow and then running the `Setup CI` workflow.

**Comment by whoabuddy** [comment]
@AnandChowdhary I am getting the same error, I was able to set up the repo and push my first commit, but changing the config afterward resulted in errors.

OS: Linux Mint 20.1
Browser: Brave
Version: 1.21.76
Chromium: 89.0.4389.86 (Official Build) (64-bit)

For me the error happens in Step 5: 

- [Error in first run](https://github.com/JoinFreehold/freehold-status/runs/2237725659?check_suite_focus=true#step:5:38)
- [Repo page](https://github.com/JoinFreehold/freehold-status)
- [Actions logs](https://github.com/JoinFreehold/freehold-status/actions)

Screenshot of errors:

![Screenshot from 2021-03-31 07-22-26](https://user-images.githubusercontent.com/9038904/113160895-be8da880-91f2-11eb-977c-1aee7b1c530c.png)

I confirmed the GitHub PAT includes the workflows permissions as requested, but I did see this in the [logs for Step 4](https://github.com/JoinFreehold/freehold-status/runs/2237725659?check_suite_focus=true#step:4:68):

```
! [remote rejected] master -> master (refusing to allow a GitHub App to create or update workflow `.github/workflows/response-time.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/JoinFreehold/freehold-status'
```

Following that is an `UnhandledPromiseRejectionWarning` [in Step 4](https://github.com/JoinFreehold/freehold-status/runs/2237725659?check_suite_focus=true#step:4:98) also referencing the "commit" value.

```
(node:2874) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'commit' of undefined
    at Object.getResponseTimeForSite (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.1/dist/helpers/calculate-response-time.js:62:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.generateSummary (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.1/dist/summary.js:39:1)
(node:2874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

Finally, I can confirm that @andrewsouthard is correct, if I run the `Response Time CI` workflow manually, then run the `Setup CI` workflow, then they were both successful. :shrug:

**Comment by nijel** [comment]
Same here, happened after changing config (adding a site to monitor): https://github.com/weblate-status-bot/status/actions/runs/766933728

The workaround described in https://github.com/upptime/upptime/issues/262#issuecomment-803315321 (running `Response Time CI` manually) worked for me as well.

**Comment by AnandChowdhary** [comment]
I just pushed an update that should fix this!

**Comment by gaeljw** [comment]
Was still happening to me but workaround to trigger _Response Time CI_ manually worked as well.
