### ISSUE TITLE
Example: Scheduled maintenance tomorrow

### ISSUE THREAD

**Issue by AnandChowdhary** [upptime/upptime#267]
This is an example of how you can set up a scheduled maintenance event. To set this up, create a new issue in your @upptime repository and add the label `maintenance` to it. Then, you can add details in the comments. Make sure you also add an HTML comment at the beginning of the issue, which looks like this:

```html
<!--
start: 2021-02-24T13:00:00.220Z
end: 2021-02-24T14:00:00.220Z
expectedDown: google, hacker-news
-->
```

More here: https://upptime.js.org/docs/scheduled-maintenance

**Comment by AnandChowdhary** [comment]
Our API will likely be down tomorrow from 1 pm to 2 pm UTC because we're migrating to a new host.

**Comment by adambotfd** [comment]
ok
