### ISSUE TITLE
Bug: All systems are operational is showed twice

### ISSUE THREAD

**Issue by ririko5834** [upptime/upptime#270]
All systems are operational is showed twice:
![image](https://user-images.githubusercontent.com/64729293/109264278-06409f00-7805-11eb-9443-fef8aee5745c.png)

**Comment by AnandChowdhary** [comment]
Can you share a link to your site? I haven't been able to reproduce this.

**Comment by thomasmerz** [comment]
I also have this problem. See https://github.com/upptime/upptime/discussions/272 and https://thomasmerz.github.io/upptime/

**Comment by AnandChowdhary** [comment]
This is now fixed, thanks!

**Comment by ririko5834** [comment]
@AnandChowdhary Also make sure to fix this bug: https://github.com/upptime/upptime/issues/225
