### ISSUE TITLE
Issues not being created, status not updated on website

### ISSUE THREAD

**Issue by benaltair** [upptime/upptime#296]
**Describe the bug**
During the Netlify CDN outage today we had a change to test Upptime's performance on our main site. Unfortunately, we found that nothing happened.
- No notifications
- No issue created
- [Status page](https://status.bahaistudies.ca/) still said "All systems are operational" even though the [site page](https://status.bahaistudies.ca/history/association-for-baha-i-studies) said "Down"

**Expected behavior**
We expected at the very least to have an issue created when the site was marked as Down. We also hoped for notifications.

**Screenshots**
![image](https://user-images.githubusercontent.com/17771229/112528631-9f5dc980-8d61-11eb-8451-8f2bcf84c095.png)
![image](https://user-images.githubusercontent.com/17771229/112529194-3d519400-8d62-11eb-9230-980e3b2e092d.png)

**Additional context**
The repo is public here if you want to check configuration: https://github.com/bahaistudies/status

**Comment by kescherCode** [comment]
Same thing happening for https://github.com/kescherCode/status

**Comment by AngelNull** [comment]
Can replicate this issue, no issues being opened, only the individual page says "down" and total percent uptime isn't changed either, was working previously.

**Repo**: https://github.com/AngelNull/status

![img](https://i.foxgirls.cc/WkgmR2rcWzned7i.png)

**Comment by royletron** [comment]
I am also having the same problem:
https://github.com/royletron/anton-uptime

**Comment by ericdrgn** [comment]
Same experience here. Has no one even looked at this and what might be going on?

**Comment by royletron** [comment]
Hey all. I did some looking and found that when the action requests existing issues it attempts to use the URL:
```
https://api.github.com/issues?owner=royletron&repo=anton-uptime&labels=ci&filter=all&state=open&sort=created&direction=desc&per_page=1
```
To get existing issues. The problem is it doesn't look like that is the correct rest route anymore - it should be:
```
https://api.github.com/repos/royletron/anton-uptime/issues?labels=ci&filter=all&state=open&sort=created&direction=desc&per_page=1
```
I also notice that Upptime is using `17.11.2` of Octokit to do all of it's GitHub API related stuff. The current version of Octokit is `18.5.2` so there is a chance the API has been updated since and is now failing - though I can't confirm. I'd hope it might just be a case of bumping the version.

**Comment by thomasmerz** [comment]
Same here 😞 

<img width="979" alt="image" src="https://user-images.githubusercontent.com/18568381/114823593-03edd080-9dc4-11eb-9059-cc65b60854ec.png">

<img width="475" alt="image" src="https://user-images.githubusercontent.com/18568381/114823627-11a35600-9dc4-11eb-82bc-9eba5aab8867.png">

But no issue was created for this DOWN event.

👁️ See discussion started on 15 March: https://github.com/upptime/upptime/discussions/288

**Comment by pietvanzoen** [comment]
Nice! Do I need to do anything to get this update? Or is that just automatic?

**Comment by AnandChowdhary** [comment]
No, it should auto-update. 😀

**Comment by thomasmerz** [comment]
@AnandChowdhary , I'm still getting **no issues created**. See:
 https://github.com/thomasmerz/upptime/commit/36138f62fa508cb589330ce89f4ca225eb75df31 (DOWN 👍🏻 )
 https://github.com/thomasmerz/upptime/commit/ad18d64f97fd873d0a4c20154059de5417c50ff5 (README 👍🏻 )
 https://github.com/thomasmerz/upptime/commit/da26709b76d339c26620381e92999352051f53ac#diff-c85a6a295eb92cb65a1939e4c619a34dab41c30f0d86c0e841abe491b6a49250L204 (update summary 👍🏻 )

**Comment by fred-cardoso** [comment]
The proposed fix has not been released yet, more info here: https://github.com/upptime/uptime-monitor/pull/149#issuecomment-820469538

**Comment by soemarko** [comment]
> The proposed fix has not been released yet, more info here: [upptime/uptime-monitor#149 (comment)](https://github.com/upptime/uptime-monitor/pull/149#issuecomment-820469538)

Umm if the fix isn't released why close the issue? Anyway, it seems like someone has open a new thread for this same issue.

**Comment by benaltair** [comment]
> Umm if the fix isn't released why close the issue? Anyway, it seems like someone has open a new thread for this same issue.

Hasn't it been merged here? https://github.com/upptime/uptime-monitor/pull/149

**Comment by kescherCode** [comment]
It has been merged into the git tree of that module, yes. However, the upptime template doesn't seem to use it, or something else causes this issue to persist. It also still persists for https://github.com/kescherCode/status

**Comment by AnandChowdhary** [comment]
The fix has been released, but if it's not in your repository, please do this manually:

1. Find and replace `GITHUB_TOKEN` with `GH_PAT` in your `.github/workflows/update-template.yml`
2. Run Update Template CI [manually](https://upptime.js.org/docs/triggers)
3. This should auto-update your Upptime to the latest version, which both fixes the updating problem and now throws an error in case the update couldn't be pushed.
