### ISSUE TITLE
"An error occurred" on new status website

### ISSUE THREAD

**Issue by CompuGenius** [upptime/upptime#297]
**Describe the bug**
I just generated a new [status website](https://status.goldencheck.org) following the Getting Started docs, yet after I updated the comfiguration file, the site now redirects to [a 404](https://status.goldencheck.org/error). The Github readme itself shows the statuses just fine, which leads me to believe it's an issue with the custom domain, however, it does show the proper nav links and icon.

**To Reproduce**
1. Go to https://status.goldencheck.org
2. See error

**Expected behavior**
A proper status page, such as https://status.shulert.com/

**Screenshots**
![image](https://user-images.githubusercontent.com/39806174/112694293-7c621100-8e58-11eb-927d-e7b26c232c4f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 11
 - Browser: Firefox

**Comment by agarwalBinay18** [comment]
Can I work on this  issue?

**Comment by CompuGenius** [comment]
Please do!

**Comment by CompuGenius** [comment]
#283 This fixes the issue! It needs to be the organization name if hosted on an organization! @AnandChowdhary, please merge!
