### ISSUE TITLE
Generated README badges point to this repo instead of the proper one

### ISSUE THREAD

**Issue by ShulertApp** [upptime/upptime#306]
**Describe the bug**
When the README is generated, it points the badges of the workflows to this repo (upptime/upptime) instead of the proper repo. Also, although this could just be because I made a mistake at first, it points the link to the image of the badge to the user instead of the organization, but that may be because I was confused before #283

**To Reproduce**
1. Generate new status page
2. Look at README code
4. See problem

**Expected behavior**
I expect it to properly link to the correct worksflows and image links.

**Comment by Siddhant-K-code** [comment]
Are you talking about these Badges: 
![image](https://user-images.githubusercontent.com/55068936/114199374-dd6a0880-9971-11eb-9a7c-121e624b0669.png)

I think it refers to the workflow run where it gets executed, i.e. Action ( workflow ) section of upptime. 

I think this can be easily fixed!

**Comment by ShulertApp** [comment]
> 
> 
> Are you talking about these Badges:
> 
> ![image](https://user-images.githubusercontent.com/55068936/114199374-dd6a0880-9971-11eb-9a7c-121e624b0669.png)
> 
> I think it refers to the workflow run where it gets executed, i.e. Action ( workflow ) section of upptime.
> 
> I think this can be easily fixed!

I am, indeed. I believe it just needs to be added to the code that updated the README to also update the badges to the appropriate repo. It shouldn't be too hard.

**Comment by Siddhant-K-code** [comment]
i was going through the code, i think: https://github.com/upptime/uptime-monitor/blob/master/src/summary.ts

is generating README.md i am unable to figure in which part inside it?

**Comment by Siddhant-K-code** [comment]
@AnandChowdhary Pls Review!

**Comment by CompuGenius** [comment]
That's great, thanks 👍

**Comment by Siddhant-K-code** [comment]
It was wrong : https://github.com/upptime/uptime-monitor/pull/146#issuecomment-816886222

what will be the changes then? Any Suggestions?

**Comment by Siddhant-K-code** [comment]
I think we have to change `owner` && `repo` in https://github.com/upptime/uptime-monitor/blob/master/src/helpers/workflows.ts#L19-L20 

which is getting used in https://github.com/upptime/uptime-monitor/blob/master/src/update-template.ts#L19 

i think `owner,repo` should be replaced with `${owner}`

@AnandChowdhary Sir, Could pls confirm?

**Comment by Siddhant-K-code** [comment]
or, we can add an `update-template.yml` file for updating the CI build status part of README.md

**Comment by gitgrub** [comment]
This is fixed now, merci.
