### ISSUE TITLE
ERROR RequestError [HttpError]: API rate limit exceeded for 52.233.70.33. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

### ISSUE THREAD

**Issue by soneji** [upptime/upptime#309]
Pretty much once a day, every day, I get this error in a github actions run

ERROR RequestError [HttpError]: API rate limit exceeded for 1.2.3.4. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

See example: 

https://github.com/iskconpandavasena/uptime/runs/2312397733?check_suite_focus=true

Is there anything that can be done? I notice it is already using the github token, so why is it showing this error 🤔

**Comment by soneji** [comment]
And this one's fully broken, maybe? 

https://github.com/soneji/uptime/runs/2313877666?check_suite_focus=true

![image](https://user-images.githubusercontent.com/12625848/114281160-b1fc2200-9a34-11eb-80d5-4e1b75313e0d.png)

**Comment by Siddhant-K-code** [comment]
The public GitHub API requests are limited to 60 / hour / IP, as you observed.

I think that a GitHub workflow that can be used to spam API too. so Maybe sometimes it doesn't execute from some API's But, it is running now, and it was running in the next workflow, likes the workflow after 6 hrs. got executed succesfully.

**Comment by soneji** [comment]
Is there any way to stop this completely? I pretty much get an email and notification from github every day about several failed runs

**Comment by ConcurrentHashMap** [comment]
@AnandChowdhary This seems to relate to https://github.com/upptime/upptime/issues/287, I'm also having issues since several days now.

**Comment by AnandChowdhary** [comment]
The fix has been released, but if it's not in your repository, please do this manually:

1. Find and replace `GITHUB_TOKEN` with `GH_PAT` in your `.github/workflows/update-template.yml`
2. Run Update Template CI manually
3. This should auto-update your Upptime to the latest version, which both fixes the updating problem and now throws an error in case the update couldn't be pushed.

**Comment by soneji** [comment]
Thank you @AnandChowdhary it has appeared to work :) 

I will reopen this issue if the bug persists
