### ISSUE TITLE
Outage issues not being created (seeing an API request return 404)

### ISSUE THREAD

**Issue by BBaoVanC** [upptime/upptime#311]
**Describe the bug**
Issues are not being created when outages happen.

**To Reproduce**
1. Have an outage
2. Check your issues page and actions page

**Expected behavior**
I expect an issue to be created as intended.

**Additional context**
I noticed that in the actions log, there's an API request which returns a 404 (see [an example on my status page](https://github.com/BBaoVanC/status.bbaovanc.com/runs/2359375254#step:3:35)). It looks like this is what's preventing the issue from being created, or at least part of the issue.

**Comment by everwanna** [comment]
I have the same problem when getting a 403 error.

The status page said it was down, but no issue created.
