### ISSUE TITLE
Runner Ignored

### ISSUE THREAD

**Issue by MrBenFTW** [upptime/upptime#312]
After adding to runner: ` [self-hosted, Linux, X64]` to `.upptimerc.yml` the GitHub actions are not using my runner. Do I need to modify each action to use it manually? I need to use my own runner as I have strict firewalls setup. 

In each runner file there is a warning not to edit it manually so I am not sure what to do?

<img width="538" alt="image" src="https://user-images.githubusercontent.com/27426792/115058972-c54c3900-9edd-11eb-81f2-8e3893d775b5.png">
<img width="977" alt="image" src="https://user-images.githubusercontent.com/27426792/115058997-d1d09180-9edd-11eb-90a3-b28d329fd054.png">

**Comment by MrBenFTW** [comment]
I'm also using a fresh server to use as a GitHub worker, what dependencies do I need? So far I've installed git and node/npm

**Comment by AnandChowdhary** [comment]
Can you try a string instead, like:

```yaml
runner: "[self-hosted, Linux, X64]"
```

**Comment by MrBenFTW** [comment]
> Can you try a string instead, like:
> 
> ```yaml
> runner: "[self-hosted, Linux, X64]"
> ```

I will try that in a minute, what dependencies does the server need to have installed? Node etc.

**Comment by AnandChowdhary** [comment]
> what dependencies does the server need to have installed?

Yeah, that's a great question, but I have absolutely no idea. 🤷 I have no experience setting up a custom runner!

**Comment by MrBenFTW** [comment]
Can confirm that putting the runner in a string solved the issue.
