### ISSUE TITLE
Repository secrets not being passed

### ISSUE THREAD

**Issue by fred-cardoso** [upptime/upptime#319]
**Describe the bug**
I am using a couple of repository secrets and after the last update they are not working (not being passed to the URL and the request headers).

**To Reproduce**
1. Create a simple GET method on the upptimerc.yml file
2. On the URL, append the Secret Key to the url, like /?test=$YOUR_KEY
3. The server logs show this:
![image](https://user-images.githubusercontent.com/32043667/115432301-2174cd00-a1fe-11eb-90f1-76ff79abf94f.png)

**Screenshots**
My keys are defined under Repostitory Secrets:
![image](https://user-images.githubusercontent.com/32043667/115432376-32bdd980-a1fe-11eb-8158-9542e2e66c82.png)

**Additional context**
I also tried with ${{ secrets.HK_TOKEN }} but the result is the same.

**Comment by robingenz** [comment]
I seem to have the same problem.
I am using environment variables for my URLs.
The uptime check fails with the following error:
```
 Got an error (on error) [Error: Couldn't resolve host name]
```
Example: https://github.com/robingenz/upptime/runs/2393776751?check_suite_focus=true (see `Check endpoint status`)

**Comment by AnandChowdhary** [comment]
My fault! I've deployed the fix now!

**Comment by fred-cardoso** [comment]
Thank you for the fast fix @AnandChowdhary !

Is the release process automatic or do you have to trigger the GH action?

**Comment by AnandChowdhary** [comment]
Yes, your repo will auto-update within 24 hours. You can also manually run the "Update Template CI" workflow to update it instantly.

**Comment by fred-cardoso** [comment]
Yeah I know that part 😄 
I was asking if the process on the "main" repo upptime/upptime is also done every 24H or if it's manually done. I manually triggered the Update Template CI and it's still on version 1.26.2.

Sorry for the trouble. Thank you 😉

**Comment by AnandChowdhary** [comment]
No, the `upptime/upptime` repo uses the `master` branch of the workflow instead, so it's always on the latest version!

**Comment by robingenz** [comment]
@AnandChowdhary Thank you very much! 🎉
