### ISSUE TITLE
Bug: tcp-ping does not produce outage

### ISSUE THREAD

**Issue by kescherCode** [upptime/upptime#328]
**Describe the bug**
When a host is down and tcp-ping is used to check for its availability, even though the Uptime CI log clearly shows this host as being down, a "Skipping commit, status is up" message appears.
https://github.com/kescherCode/status/runs/2418249144?check_suite_focus=true#step:3:60

**To Reproduce**
1. Create a tcp-ping site like this (intentional wrong port to trigger it being down):
```
  - name: "Monero node"
    url: unova.kescher.at
    port: 23123
    check: "tcp-ping"
```
2. Wait for Uptime CI to run
3. Visit the logs and see the mistaken message

**Expected behavior**
I expected the service to be down and an issue to be created.

**Comment by gitgrub** [comment]
Yes, same here.
Different url and port for sure, but same result in the "Check status" log.
The url is not up, its not even resolved by dns, as this is a test. I am trying to track down the tcp-ping problem at my own site, that reports a not listening port as up.

**Comment by jayantkatia** [comment]
#328 is due to no checks for errors returned in the results array. Refer: [#6 of tcp-ping](https://github.com/apaszke/tcp-ping/issues/6).

**Comment by thomasmerz** [comment]
It's [merged](https://github.com/upptime/uptime-monitor/pull/157#issuecomment-992197551), so issue should/could be closed!?
