### ISSUE TITLE
Error: Input required and not supplied: token

### ISSUE THREAD

**Issue by harleykin** [upptime/upptime#334]
**Describe the bug**
I've setup a new fork of upptime at harkeykin/dotnetuptime but all of the actions are failing due to this error:

"Error: Input required and not supplied: token"

I'm going through your wiki but not seeing anything obvious that would cause this error.  What am I doing wrong?

**To Reproduce**
1. Update the config file
2. Wait for action to run or manually kick off

**Expected behavior**
I expected it to look like your examples. :(

**Screenshots**

![image](https://user-images.githubusercontent.com/2998848/116108838-e51bf380-a679-11eb-8fda-ba460963ff12.png)
![image](https://user-images.githubusercontent.com/2998848/116108905-f2d17900-a679-11eb-8e96-24b44f72dac7.png)
![image](https://user-images.githubusercontent.com/2998848/116108621-b140ce00-a679-11eb-82b9-788ef2e6fbf8.png)

**Comment by AnandChowdhary** [comment]
Did you add your GitHub token `GH_PAT`?

**Comment by harleykin** [comment]
OMG you're right.  I never finished doing that.  Now everything looks green.  I'm blind apparently LOL.

Thank you!  :D

**Comment by Fatichti** [comment]
hey
i add my github token to secret envt GH_PAT but still get the error
