### ISSUE TITLE
CNAME Unexpected token .

### ISSUE THREAD

**Issue by MrBenFTW** [upptime/upptime#337]
I am trying to build the static site, however It keeps failing. Sometimes the index.html file contains `404` but most times it is not committed.

Checking the action log shows this:
```
/home/runner/actions-runner/_work/AestherNetwork/AestherNetwork/site/pre-process.ts:13
63
    if (config["status-website"]?.cname)
```
<img width="959" alt="image" src="https://user-images.githubusercontent.com/27426792/116372687-951d6800-a804-11eb-9bb9-7b9f0b1ba6db.png">

**Comment by MrBenFTW** [comment]
Further up I am seeing this:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
45
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
46

45
added 1406 packages from 1363 contributors, removed 1 package and audited 1468 packages in 16.057s
```

**Comment by MrBenFTW** [comment]
Full log: https://pastebin.com/raw/FRjMkvM1

**Comment by AnandChowdhary** [comment]
Aah, it looks like a Node.js version issue. We're using the `?.` operator that's not supported in your runtime. I can perhaps stop using that in the source, or maybe you can try using Node.js 14?

**Comment by MrBenFTW** [comment]
Updated to NodeJS 16 and all is well now, will close the ticket. Seems like debian/ubuntu come default to NodeJS 10 or 11 when installed with Apt.

This is on a self hosted runner
