### ISSUE TITLE
Custom User-Agent when checking sites

### ISSUE THREAD

**Issue by mochaaP** [upptime/upptime#340]
**Describe the bug**
When a `User-Agent` blocking strategy is configured on the site (e.g. scrawlers blocking), upptime will report a false downtime.

**To Reproduce**
1. Set a User-Agent filter on the server with the following regex:
```regex
/Bot|Spider|BingPreview|Feedfetcher-Google|ia_archiver|MBCrawler|Mediapartners-Google|MSNot-media|Teoma|Yahoo! Slurp|^$/i
```
2. Trigger CI
3. See error

**Expected behavior**
Return status code 444.
Users can set a custom User-Agent string.

**Additional context**
<https://github.com/upptime/uptime-monitor/blob/master/src/helpers/request.ts#L23>

Setting headers manually in config won't resolve this problem, as the `User-Agent` string was set through `CURL_SETOPT`, which have a higher priority than headers.

**Comment by jayantkatia** [comment]
@mochaaP 
Uptime monitor sets config provided headers using ```CURL_SETOPT ``` as well. 
See https://github.com/upptime/uptime-monitor/blob/master/src/helpers/request.ts#L15

Tinkering with #226, i found that config provided headers (User-Agent) will take priority.
