### ISSUE TITLE
Websites is showing as complete outage

### ISSUE THREAD

**Issue by maxbooiii** [upptime/upptime#343]
**Describe the bug**

all my sites is showing as `Complete outage`, while they're not down at all, they're all online. they're not even down, they work completely fine. so this shouldn't show as `Complete outage`.

**Comment by AnandChowdhary** [comment]
Link?

**Comment by maxbooiii** [comment]
> Link?

[here if you mean github.](https://github.com/maxbooiii/status) or [my custom url page](https://status.mewtwothebot.com/)

**Comment by AnandChowdhary** [comment]
As you can see here: https://github.com/maxbooiii/status/commit/d8add87b45dc2b16bda0b0a3d3ace5b7c80087dc, we're getting a HTTP 503 error from these endpoints, so it's marked as down (rightly so). Can you think of why (proxy, robots, etc.) why they respond this way?

**Comment by maxbooiii** [comment]
> As you can see here: [maxbooiii/status@d8add87](https://github.com/maxbooiii/status/commit/d8add87b45dc2b16bda0b0a3d3ace5b7c80087dc), we're getting a HTTP 503 error from these endpoints, so it's marked as down (rightly so). Can you think of why (proxy, robots, etc.) why they respond this way?

Can't seem to be on my end. i've checked cloudflare and my server and all that... i see nothing that causing it 503. since all services are up and running as normal.🤔

**Comment by DillFrescott** [comment]
I tried out Upptime and all 4 of my sites showed up as totally down. I even completely reinstalled Upptime and it still happened. Made me jump ship.

**Comment by LordRandom** [comment]
From my testing it looks like cloudflare "Bot Fight Mode" is blocking the status check bot and presenting a captcha challenge

**Comment by maxbooiii** [comment]
> From my testing it looks like cloudflare "Bot Fight Mode" is blocking the status check bot and presenting a captcha challenge

Yea this seemsed to solve this. thanks.

**Comment by MohamedElashri** [comment]
Is there a workaround for cloudflare `Bot Fight Mode` except disabling ?

**Comment by maxbooiii** [comment]
> Is there a workaround for cloudflare `Bot Fight Mode` except disabling ?

I never found any workaround this. so i doubt it.

**Comment by icedterminal** [comment]
@MohamedElashri  @ltzmax 

See #785 

It's not perfect but it works.

**Comment by AnandChowdhary** [comment]
This is definitely very interesting; I don't know if it's practical for us to try and get into Cloudflare's verified bot program, but we do use a custom header. Maybe there's a Cloudflare "Page Rule" we can setup to allow requests with that user-agent?

**Comment by icedterminal** [comment]
> I don't know if it's practical for us to try and get into Cloudflare's verified bot program

The bot would need to be controlled to a level that no one could abuse it. If you haven't seen it, here is the form: https://docs.google.com/forms/d/e/1FAIpQLSdqYNuULEypMnp4i5pROSc-uP6x65Xub9svD27mb8JChA_-XA/viewform

> Maybe there's a Cloudflare "Page Rule" we can setup to allow requests with that user-agent?

Page Rules do not offer a User-Agent field. I'm still looking alternatives versus just whitelisting an entire ASN. I have seen in server logs people deploy bad bots, sniffers, etc. on Microsoft's hosting.
