### ISSUE TITLE
owner name does not update in README.md

### ISSUE THREAD

**Issue by marchingon12** [upptime/upptime#344]
**Describe the bug**
After setting the owner name in .upptimerc.yml as 'marchingon23', github-actions does not change the owner name under README.md after renaming name to 'marchingon12', hence all links are 'wrong'.

**To Reproduce**
1. Go to .upptimercyml and edit owner name.
2. Commit changes & push.
3. Wait for github-actions to finish.
4. Check README.md and check links and entities that require owner name.

**Expected behavior**
Change the owner name in the README.md to match the one in .upptimercyml

**Screenshots**

upptimerc.yml:
![firefox_GrT06Dd8kH](https://user-images.githubusercontent.com/41235480/116602084-c6885780-a91a-11eb-81ed-5e5f7d7bd18f.png)

Generated README.md:
![firefox_vf4QJ3a60C](https://user-images.githubusercontent.com/41235480/116601997-a3f63e80-a91a-11eb-9911-b108f37f5856.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22]  88.0

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Huawei Mate 20
 - OS: [e.g. iOS8.1] Android 10
 - Browser [e.g. stock browser, safari] Chromium
 - Version [e.g. 22] 90

**Additional context**
I like upptime a lot :D

**Comment by jayantkatia** [comment]
Hi @marchingon12, I too like upptime a lot :smile: 

### How this works?
The very first run of  ```SETUP CI``` has a step which updates a part of  ```README.md``` from ```<!--start: description-->  Koj description <!--end: description-->```  to  ``` new description ```.

### Why subsequent updates to the description are not made?
Uptime Monitor only sees something wrapped between ```<!--start: description-->``` and ```<!--end: description-->``` as description. On the subsequent update, it finds no description comments and hence does not updates.

### Solutions (until fixed officially) 
#### 1. Manually update Readme (recommended) :laughing: 
#### 2. Add description comments
Manually add comments and trigger ```SUMMARY CI```
Refer [Upptime template's readme](https://raw.githubusercontent.com/upptime/upptime/master/README.md) for html comments.

Doing this, will generate a readme with the below lines written twice (one from the first run of ```SETUP CI``` and one from the latest run).
 
```With Upptime, you can get your own unlimited and free uptime monitor and status page, powered entirely by a GitHub repository. We use Issues as incident reports, Actions as uptime monitors, and Pages for the status page.```

You need to delete the duplicate lines manually :cry: 
### Is this a bug?
Its debatable.
#### Yes
1. Unless comments are manually omitted, changes to Repo name and Github usernames should be automatically accounted.
2. If auto generated description is unwanted, we can always omit the comments manually. 
#### No
1. Changes to Repo name and Github usernames are very rare. Maintainers can edit those manually.


What do you think @AnandChowdhary and @marchingon12? Is this a bug? Must we have this automatically updated?
If yes, I would like to work on it.

**Comment by AnandChowdhary** [comment]
Thanks for the thorough comment! Maybe we can just write better docs on letting people know they'll have to update this manually, or have an easier way to update it manually using CI?

**Comment by jayantkatia** [comment]
Agreed, generally users do update the readmes manually.
Also, I am planning to propose a solution by making some changes to [summary.ts](https://github.com/upptime/uptime-monitor/blob/master/src/summary.ts). If its turns out to be effective and viable, I will be happy to have it merged.

**Comment by Nirmitjatana** [comment]
I faced the same issue when I accidentally added a wrong `baseUrl:` and when I tried changing, README wasn't fixed and went about updating the README manually. Maybe we can automate this process @AnandChowdhary
