### ISSUE TITLE
Fatal JS error on page load

### ISSUE THREAD

**Issue by PrivateGER** [upptime/upptime#346]
**Describe the bug**
A fatal JavaScript error occurs on page load.
The graphs and status indicators are not loaded and stuck on the loading icon.

**To Reproduce**
1. Run the "Setup CI"
2. Fatal JS error

**Screenshots**
https://i.imgur.com/r8ryUeI.png

**Additional context**
This happened after the navbar was apparently doubled(?) and the Setup CI was re-run in an attempt to fix the issue.

**Comment by BBaoVanC** [comment]
Just edited my upptimerc and I'm getting this issue now.

**Comment by marchingon12** [comment]
Same

**Comment by haliliceylan** [comment]
same here.

**Comment by AndrewLaneX** [comment]
Seems the [demo site](https://demo.upptime.js.org/) also has this issue.

**Comment by wgyt** [comment]
Same on my status sites

**Comment by AnandChowdhary** [comment]
Same on my site(s) 😭

**Comment by AnandChowdhary** [comment]
No idea what caused this, no dependencies updated or new releases to the status page repo, so this is definitely out of the ordinary. Having a look!

**Comment by PrivateGER** [comment]
Fixed on "Setup CI" rebuild.
