### ISSUE TITLE
Responsiveness: button overflow at x-axis & image hiding the text

### ISSUE THREAD

**Issue by sakshi-choudhary** [upptime/upptime#363]
**Describe the bug**
In the [documentation website](https://upptime.js.org/), there's a responsiveness issue at `breakpoints : 340px-475px`. 
Due to the size not being adjusted a/c to the breakpoints, the two buttons are creating an overflow in the x-axis.
And the text below the two buttons gets hidden by the image below it.

**To Reproduce**
1. Go to [documentation website](https://upptime.js.org/)
2. Open Chrome developers tools/ open in a mobile phone.
3. Go to breakpoints `340px-475px`.

**Expected behavior**
The button size and the text position/margin should get adjusted a/c to the breakpoints.

**Screenshots**

<img  width="327" alt="Screenshot 2021-05-18 at 12 17 51" src="https://user-images.githubusercontent.com/66865329/118607041-c1aa1b80-b7d5-11eb-9430-13d70331b629.png">
<img   width="327" alt="Screenshot 2021-05-18 at 12 17 51" src="https://user-images.githubusercontent.com/66865329/118608121-fbc7ed00-b7d6-11eb-9f82-3c411b7d9ac2.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version 90.0

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS 14.1
 - Browser safari
 - Version 14

**Additional context**
To resolve this issue we can give proper css to the `.real` and `.getStarted` classes and make use of media queries or a relative sizing.

**Comment by sakshi-choudhary** [comment]
@AnandChowdhary I would like to resolve this issue.

**Comment by AnandChowdhary** [comment]
Happy to accept a PR!

**Comment by sakshi-choudhary** [comment]
Sure, will be getting back with a PR soon.

**Comment by wgyt** [comment]
Can reproduce on latest version of Chrome IOS on an iPhone 6s.
![4C4BFC54-4801-4B60-AC31-1DC6E101AE55](https://user-images.githubusercontent.com/68466727/121004482-bdca4300-c75c-11eb-9d7b-38d764027cef.png)
