### ISSUE TITLE
Way to enable gh-pages branch after using this template?

### ISSUE THREAD

**Issue by jeyraof** [upptime/upptime#38]
After using this template, I've completely setup my `.upptimerc.yml` and also inserted GH_PAT to project's sercret.
But gh-pages is not automatically generated and `[skip ci]` message was shown.
How can i deal with it?

**Comment by AnandChowdhary** [comment]
Can you show me your repository? I'll have a look.

In general, you have to go to Settings -> GitHub Pages -> Choose the `gh-pages` branch as the source.

**Comment by gerslun** [comment]
From what I can tell, you added the `GH_PAT` token after your updated the `.upptimerc.yml`. You can go to the "Actions" tab on your repo and re-run the "Static Site CI" workflow.

**Comment by jeyraof** [comment]
@AnandChowdhary @gerslun Thank you. I've forked entire branches including gh-pages from this template repository, and then It works correctly!
