### ISSUE TITLE
Feature to hide Response Time

### ISSUE THREAD

**Issue by remyduthu** [upptime/upptime#398]
### Discussed in https://github.com/upptime/upptime/discussions/376

<div type='discussions-op-text'>

<sup>Originally posted by **roim** June  3, 2021</sup>
Upptime has been great for us, I just wish I could hide response times. I found that the latencies reported from GitHub's runners are both inconsistent and inaccurate:

- They mostly depend on where the runner is located (some runs hit our servers in the us east cost, some in west, both with widely different latencies).
- Some external factors such as DNS can cause swings due to caching.
- etc

I've seen runs ranging from 20ms to 800ms, even though our own servers measure the same processing time of <10ms. We could mitigate this by having our own runners, but for a status page I'd rather have as little of my own infra as possible.

For frontend webpages, especially those served on a CDN, the current behavior is probably OK, but when we are measuring our API endpoints (which regularly have <10ms latency), seeing 20-800ms swings makes the reported value almost meaningless and I wish I could just hide it.

What do people here think of disabling response time reports, either globally or per site? I wouldn't mind putting up some PRs (but no promise on when).</div>

**Comment by raykai** [comment]
i would love this option too

**Comment by modem7** [comment]
+1 on this. 

It's definitely a wild swing that's just not correct. I typically don't get less than 100, and usually 300-400ms is average for mine, which isn't correct for the users of my status page.

**Comment by AnandChowdhary** [comment]
We'll add this in the upcoming version for sure!

**Comment by remyduthu** [comment]
I’ve created the pull request for this feature: https://github.com/upptime/status-page/pull/296
