### ISSUE TITLE
every site is strange

### ISSUE THREAD

**Issue by belhyun** [upptime/upptime#40]
![image](https://user-images.githubusercontent.com/895026/97383060-135d8800-1910-11eb-8beb-65f8f21e21ac.png)

status is hanged

**Comment by sebastianroming** [comment]
Facing the same issue, no matter what I've tried to configure, the status page always tries to load files from `/status-website/*`. I've set up a custom Domain (CNAME) for the repo and commented the `baseUrl` property.

**Comment by sebastianroming** [comment]
@AnandChowdhary Thanks for this quick fix, but I'm not sure this works as expected, as the **Static Site CI** issues the following error (but still succeeds):

```
/home/runner/work/[REPONAME]/[REPONAME]/site/status-page/__sapper__/build/server/server.js:27710
let config$1 = jsYaml.safeLoad(fs__default$1['default'].readFileSync(join(".", ".upptimerc.yml"), "utf8"));
                                                        ^

ReferenceError: join is not defined
    at Object.<anonymous> (/home/runner/work/[REPONAME]/[REPONAME]/site/status-page/__sapper__/build/server/server.js:27710:57)
```

**Comment by sebastianroming** [comment]
@AnandChowdhary Now the deployment works, the files are getting loaded as expected. But the status page now just states an Error 404, without content (or uptimes).

**Comment by AnandChowdhary** [comment]
Thanks for the reports! If you try running the Static Site CI again, it should work now! 😄 This got broke as I added support for publishing under subdirectories last night, but should be all fixed now.

I've tested it here:

More about how to run Static Site CI and other workflows: https://github.com/upptime/upptime/runs/1320528347
