### ISSUE TITLE
Topics get updated regardless of skipTopicsUpdate setting

### ISSUE THREAD

**Issue by nutjob4life** [upptime/upptime#400]
## 🐛 Describe the bug

When `skipTopicsUpdate` is `false`, the topics on an Upptime project get updated, as expected. However, when `skipTopicsUpdate` is `true`, they _also_ get updated, which is unexpected.

## 📝 To Reproduce

1. In your `upptimerc.yml` file, set `skipTopicsUpdate` to `true` in the `status-website` section.
2. Commit and push this change.
3. Manually set your topics on your GitHub repository to a preferred set, such as `status`, `service-level-agreement`, `availability`, etc..
4. Wait 5 minutes; your topics get reset to `uptime-monitor`, `status-page`, and `upptime`.

## 🤔 Expected behavior

The manually set topics should be left alone.

## 🌁 Screenshots

![Screen Shot 2021-07-15 at 4 10 26 PM](https://user-images.githubusercontent.com/814813/125858215-14562311-e25c-45ef-9b3d-d7bdbe6174fd.png)

## 🧩 Additional context

This is an admittedly minor—if not minuscule—detail.

**Comment by jayantkatia** [comment]
According to https://github.com/upptime/uptime-monitor/blob/master/src/summary.ts#L257, ```upptime``` topic is mandatory.
You may omit ```uptime-monitor``` and ```status-page```.

Since Up-time management is a crucial aspect, the mandatory topic helps keep track of repositories using ```Upptime```. The maintainers might use this to inform us of breaking changes that the ```Update CI``` workflow could not handle.

**Comment by nutjob4life** [comment]
Okay so two issues:

- The [documentation](https://upptime.js.org/docs/configuration#repository-metadata) should mention this.
- It doesn't seem to work; I included `upptime` and my own custom topics, but they all got overwritten with `uptime-monitor`, `status-page`, and `upptime`.

**Comment by jayantkatia** [comment]
Its peculiar :thinking: .I have only ```upptime``` and my custom topics, and they don't get overwritten. 
Check out my [Repo](https://github.com/jayantkatia/status).
 
Can you share some more details so that we can look into it?

**Comment by nutjob4life** [comment]
AH.

Thanks @jayantkatia  for sending your repo. I see the issue: my `skipTopicsUpdate` is in `status-website`, not at the top level as it is in yours! Testing … yes, if I move `skipTopicsUpdate` to the top level, then it works fine: `upptime` stays in addition to my custom tags 😳

I'm going to close this with resolution [pebkac](https://en.wikipedia.org/wiki/User_error#PEBKAC/PEBCAK). Sorry for wasting everyone's time 😞

**Comment by jayantkatia** [comment]
I'm glad, it helped!
