### ISSUE TITLE
uptime ci trigger is stange

### ISSUE THREAD

**Issue by belhyun** [upptime/upptime#42]
![image](https://user-images.githubusercontent.com/895026/97513881-b5dd4000-19d0-11eb-8344-8587862c1100.png)

The uptime CI should run every 5 minutes, but it doesn't seem to run every 5 minutes as in the image above. Do you need any other settings?

**Comment by AnandChowdhary** [comment]
Unfortunately not, GitHub sometimes runs it slower, they probably schedule a job every 5 minutes for all the actions and run some in parallel, so it takes longer than "every 5 minutes", though that is what is requested. This is the fastest we can run it. 😄

**Comment by AnandChowdhary** [comment]
Also, it's worth noting that it's probably running close to once every 5 minutes. GitHub formats the hours, so "2 hours ago" and "2 hours ago" probably mean, for example, 13:30 and 13:35, both "approximately two hours ago" but in 5 minute intervals. You can hover over that formatted time to see the exact time it ran.

**Comment by belhyun** [comment]
Thank you. In order to execute correctly every 5 minutes, I ran a build job with jenkins and executed a POST request.

**Comment by r-chris** [comment]
I would like to re-open this issue and have the strong impression that the cron interval of 5 minutes is not even fulfilled in the demo setup. This is the history of my scheduled GitHub Actions (which were expected every 5 Minutes):

<img width="855" alt="image" src="https://user-images.githubusercontent.com/18341652/105455634-1bfdfa00-5c84-11eb-84e1-65ce9f87ae9e.png">

You can see the execution happening about **once** every hour. I do not believe this has anything to do with GitHub displaying coarse intervals - in that case you should see about 12 executions with "1 hour ago" and another 12 at "2 hours ago", right?

**Comment by AnandChowdhary** [comment]
@r-chris The problem is not that GitHub is not correctly showing the time, but that GitHub is not triggering the scheduled workflow on time. [We ask GitHub](https://github.com/upptime/upptime/blob/master/.github/workflows/uptime.yml#L13) to run the Uptime CI workflow every 5 minutes, and GitHub puts it in a queue and triggers it whenever they have an empty machine.

More issues dealing with this:

- https://github.com/upptime/upptime/discussions/193
- https://github.com/upptime/upptime/discussions/199
- https://github.com/upptime/upptime/discussions/112

External resources supporting this:

- https://stackoverflow.com/a/63192190/1656944
- https://github.community/t/cron-job-actions-not-scheduling-properly/145662
- And from https://github.community/t/no-assurance-on-scheduled-jobs/133753:

> Generally the delay time is about 3 to 10 minutes. Sometimes it may be more time, even dozens of minutes or more than one hour. However, if the delay time is too long, the scheduled workflow may be not triggered at that day.

**Comment by r-chris** [comment]
Ok, I see - do you think this issue would be resolved if we use self-hosted GitHub runners?

**Comment by AnandChowdhary** [comment]
Some of the teams using @upptime solved this by running a Jenkins CI job to trigger the `workflow_dispatch` event and force GitHub to run the workflow every 5 minutes. I think using self-hosted runners will likely also work, although I can't be certain.

**Comment by r-chris** [comment]
Ok, thank you - I will have a look at that workaround as well.

**Comment by AnandChowdhary** [comment]
I did a quick blog post with a summary: https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working

**Comment by JelmerOffenberg** [comment]
Does anyone know if there is a different in the guarantees for the enterprise organisations?

**Comment by crstauf** [comment]
I setup a self-hosted runner to attempt to have the uptime check be more reliable, but here I am waiting for a run 15 minutes after the last one.

`.upptimerc.yml`:
```yml
status-website:
  workflowSchedule:
    uptime: "*/5 * * * *"
```

**Comment by crstauf** [comment]
Finally had a subsequent run of the _Uptime CI_ workflow, 25 minutes between runs. It would seem that a self-hosted runner is no more reliable than GitHub's runner. 😞

**Comment by crstauf** [comment]
I setup a free [Cloudflare Worker](https://workers.cloudflare.com/) with a [cron trigger](https://developers.cloudflare.com/workers/platform/cron-triggers) to send the `respository_dispatch` event, and that's been working _very_ well. Now just to get the schedule to once per day (see #356).

__Cloudflare Worker__

Setup `GH_PAT` secret with GitHub personal access token, and cron trigger every five minutes.

```js
addEventListener('scheduled', function(event) {
  event.waitUntil(handleScheduled(event))
} );

async function handleScheduled(event) {
  let response = await fetch( 'https://api.github.com/repos/{owner}/{repo}/dispatches', {
    method: 'POST',
    headers: {
      'Accept': 'application/vnd.github.v3+json',
      'Authorization': 'token ' + GH_PAT,
      'Content-Type': 'application/json',
      'User-Agent': '{username},
    },
    body: JSON.stringify( {
      'event_type': 'uptime',
    } ),
  } );

  if ( 204 !== response.status ) {
    return Promise.reject( response.statusText );
  }

  return Promise.resolve( 'Success' );
}
```

**Comment by Final-Hawk** [comment]
> Cloudflare Worker to serve also as a GitHub API proxy.

Could you please share how to do that?

**Comment by Final-Hawk** [comment]
> Note: I use the same Cloudflare Worker to serve also as a GitHub API proxy. 😎
Could you please share how you achieve this?

**Comment by ririko5834** [comment]
Could anyone make guide how to use pipedream to schedule workflow dispatch? But i's not working when I tried using HTTP request to github. I have created workflow with schedule (cron) every 5 min.


![image](https://user-images.githubusercontent.com/64729293/174439940-26fd57fd-fb03-4fb2-a01b-107274017b12.png)
