### ISSUE TITLE
"Exceeded" misspelled "exceedeed" on `rate-limit-exceeded` page

### ISSUE THREAD

**Issue by torrobinson** [upptime/upptime#462]
**Describe the bug**
"Exceeded" misspelled "exceedeed" on `rate-limit-exceeded` page

**To Reproduce**
1. Go to the `/rate-limit-exceeded` page of the status page
2. The page title says "Rate limit exceedeed" rather than "Rate limit exceeded"

**Expected behavior**
The title says "Rate limit exceeded"

**Screenshots**
![image](https://user-images.githubusercontent.com/4401999/138568303-a70c6128-d052-4c0a-9901-ea521989c19b.png)

**Comment by gitgrub** [comment]
That little typo seems to be here:
https://github.com/upptime/status-page/blob/1de42c622b7dbfff66ac20524d7cd6b9e5ffa478/i18n.yml

`rateLimitExceededTitle: Rate limit exceedeed`
