### ISSUE TITLE
🛑 Secret Site is down

### ISSUE THREAD

**Issue by JonathanTreffler** [upptime/upptime#48]
In [`c4e08f6`](https://github.com/upptime/upptime/commit/c4e08f6989e0b06119c4b4b1834d28396bf95f51
), Secret Site ($SECRET_SITE) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by AnandChowdhary** [comment]
@JonathanTreffler, did you open this issue or was it opened by @upptime? I'm curious because it shouldn't have opened an issue in this repository...

**Comment by JonathanTreffler** [comment]
I didn't open it. Sorry. Don't know how this happened

**Comment by AnandChowdhary** [comment]
Very interesting! My hypothesis is that you hadn't updated your `upptime.yml` when the first Uptime CI ran, so it detected this site as down and opened an issue here. I wouldn't have expected the GitHub token to have permission to open issues, but silly me, anyone can open issues on GitHub. This is a thinker...

**Comment by JonathanTreffler** [comment]
makes sense. That may be why there is the
````
# Change these first
````
line in the template.
But thats the first thing i changed so i still don't quite understand it
