### ISSUE TITLE
/client/clientXXXX.js problem

### ISSUE THREAD

**Issue by nachosalvi** [upptime/upptime#508]
**Describe the bug**
The site no load any graph

**To Reproduce**
open site in web browser and pres f12

**Expected behavior**
How to fix acces to /client/clientXXX,js

**Screenshots**
![imagen](https://user-images.githubusercontent.com/49770936/152439647-be118e3a-7996-493c-85f7-caef56b5b093.png)

**Desktop (please complete the following information):**
  - Browser Firefox
 - Version 95.0.2

**Comment by anxolin** [comment]
My guess is that you haven't setup the `baseUrl`.

Try `baseUrl: /client`

**Comment by nachosalvi** [comment]
Sorry for the silly question.
Your answer is correct. I set baseurl to /upptime and work so fine

**Comment by anxolin** [comment]
Not silly, it just happened the same to me, that's why I know
