### ISSUE TITLE
Redirects to an un-existing error page

### ISSUE THREAD

**Issue by anxolin** [upptime/upptime#509]
**Describe the bug**
Redirects to `/error` after I enabled a custom domain in https://github.com/gnosis/cow-uptime.

It used to work before I setup the custom domain. The only changes I did was to:
- Remove the `baseUrl`
- Setup in Github pages the custom domain and  enforce HTTPS

**To Reproduce**
1. Go to https://status.cow.fi
2. Observe the redirect

I don't see anything in the console that would suggest what is the issue. I only see one `https://raw.githubusercontent.com/koj-co/upptime/master/assets/icon.svg` 404, but I believe this must come from the Github Actions plugin, because I haven't define that image. Also I see that error in the original demo too.

See https://github.com/gnosis/cow-uptime

**Expected behavior**
To not redirect and work.

**Screenshots**
![image](https://user-images.githubusercontent.com/2352112/152518865-31aacc74-e089-4aa1-ae8c-3e4904e62cde.png)

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser: Chrome and Firefox
 - Version: 97

**Comment by anxolin** [comment]
I figured it out, the repository was wrong in the config

**Comment by forever218** [comment]
i have the same question,how did you deal it?

> 我想通了，配置中的存储库是错误的

**Comment by forever218** [comment]
> i have the same question,how did you deal it?
> 
> > 我想通了，配置中的存储库是错误的

oh,now i figured it out too
