### ISSUE TITLE
Graphs issue

### ISSUE THREAD

**Issue by GrahamSH-LLK** [upptime/upptime#53]
On my site https://snapwiki.github.io/SnapWikiUptime, the graphs are buggy. When you put your cursor over the dots on the graph "7-day response time", either nothing happens, or the spot that triggers it weirdly offset. This behavior is really annoying. Please fix this!

**Comment by GrahamSH-LLK** [comment]
Weirdly enough, it doesn't happen on another (bigger) computer.

**Comment by AnandChowdhary** [comment]
I made sure the weird dots don't show up by using the client width, but the zoom-to-hover is still there, will have another look.

**Comment by GrahamSH-LLK** [comment]
> I made sure the weird dots don't show up by using the client width, but the zoom-to-hover is still there, will have another look.

Okay. Yeah, that glitch still is there....
