### ISSUE TITLE
It doesn't work. 500 error

### ISSUE THREAD

**Issue by eyoungmin** [upptime/upptime#55]
![image](https://user-images.githubusercontent.com/21292037/99337583-e6284800-28c5-11eb-9052-24b9de0e8863.png)

**Comment by AnandChowdhary** [comment]
I'm very sorry, this is now fixed. You can re-build your static site manually using [Triggers](https://upptime.js.org/docs/triggers), or it will be manually re-build within 24 hours.

It was opened yesterday in #52. I'll make sure I add some tests today itself, so we don't end up with these kind of errors again. Thanks for using Upptime!

**Comment by AnandChowdhary** [comment]
Phew, I've also added some end-to-end tests where Cypress visits http://localhost:3000 and ensures that there are status websites and also checks a single incident page: https://github.com/upptime/status-page/pull/55. These tests should take care of bugs like this before releasing. 😄
