### ISSUE TITLE
Update Template CI build failing 

### ISSUE THREAD

**Issue by zoebott** [upptime/upptime#56]
The Update Template CI is failing on the `Setup Node.js` step during the build.
![image](https://user-images.githubusercontent.com/61484383/99350588-e1c65400-28f2-11eb-960f-c73d4d5d60a3.png)

This is due to GitHub deprecating a feature as explained [here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).

The issue was raised in the Setup Node action - https://github.com/actions/setup-node/issues/212
It has been fixed in the latest version (i.e. `v2.1.2`)

**Comment by AnandChowdhary** [comment]
Hmm, this is a big problem, because even if I push an update with the updated v2.1.2, it won't "update" the template since that CI is not working anymore in all Upptime projects. Let me add the logic to update `setup-note` to [upptime/uptime-monitor](https://github.com/upptime/uptime-monitor) to make sure that it's up to date.

**Comment by AnandChowdhary** [comment]
I've added a fix that replaces `actions/setup-node@v2.1.2` with `actions/setup-node@v1.4.4` in all workflows (https://github.com/upptime/uptime-monitor/commit/c6f637618a1b4573be894bbf4f26696d6002d398). This fix runs when graphs are updated, so it should be run for all Upptime repositories within 24 hours, or if someone manually runs "Graphs CI" or "Setup CI".

**Comment by alanhamlett** [comment]
Manually running `Graphs CI` and `Setup CI` didn't seem to apply the temporary downgrade fix.

**Comment by zoebott** [comment]
To add this fix to my repository I had to do the following steps:
* Change version from `actions/setup-node@v2.1.1` to `actions/setup-node@v1.4.4` manually in `update-template.yml` and push to repository
* Run "Setup CI" workflow
* Run "Update Template CI" workflow
