### ISSUE TITLE
Dependencies in workflows need updating

### ISSUE THREAD

**Issue by modem7** [upptime/upptime#567]
Bump peaceiris/actions-gh-pages from 3.7.3 to 3.8.0
Bump actions/checkout from 2.3.3 to 3.0.2 

https://github.com/modem7/Status/pull/961
https://github.com/modem7/Status/pull/960

Each time I update them, the workflows replace them with the old versions.

**Comment by AnandChowdhary** [comment]
Happy to accept a PR here so it'll be the latest when it updates :)

**Comment by modem7** [comment]
@AnandChowdhary Would dependabot be more suitable in this particular case? That way a PR will be raised as soon as new versions of actions are out.

**Comment by Andre601** [comment]
> @AnandChowdhary Would dependabot be more suitable in this particular case? That way a PR will be raised as soon as new versions of actions are out.

While useful could it also cause spam if PRs won't get merged in time and new versions are released. This can be configured tho.
Also, not every update may be useful and could have breaking or other unwanted changes which just results in a PR being created for nothing.
