### ISSUE TITLE
500

### ISSUE THREAD

**Issue by jtprog** [upptime/upptime#58]
How can I fix this error?

`Cannot read property 'includes' of undefined`

<a href="https://ibb.co/zxZsKJN"><img src="https://i.ibb.co/4tpWBdJ/2020-11-17-21-30-32.png" alt="2020-11-17-21-30-32" border="0"></a>

**Comment by AnandChowdhary** [comment]
Closing as a duplicate of https://github.com/upptime/upptime/issues/55.
