### ISSUE TITLE
could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by pavelloz** [upptime/upptime#59]
Hey,

Im trying to set up Upptime for some of my sites but have some very weird messages coming from the static CI job ( https://github.com/pavelloz/upptime/runs/1419647547?check_suite_focus=true#step:3:29 ):

```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +7ff57fc91d084cbbdafc1bf8451edf963b35d197:refs/remotes/origin/master
  Error: fatal: could not read Username for 'https://github.com': terminal prompts disabled
  The process '/usr/bin/git' failed with exit code 128
  Waiting 18 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +7ff57fc91d084cbbdafc1bf8451edf963b35d197:refs/remotes/origin/master
  Error: fatal: could not read Username for 'https://github.com': terminal prompts disabled
  The process '/usr/bin/git' failed with exit code 128
  Waiting 12 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +7ff57fc91d084cbbdafc1bf8451edf963b35d197:refs/remotes/origin/master
  Error: fatal: could not read Username for 'https://github.com': terminal prompts disabled
  Error: The process '/usr/bin/git' failed with exit code 128
```

This is public repo, so i dont know why it needs username anyways.

Result of that is empty gh page: https://pavelloz.github.io/upptime/
And probably thats why badges of uptime are empty, because i get the same error in Setup CI workflow: https://github.com/pavelloz/upptime/runs/1419647511?check_suite_focus=true 

Did i broke something using this config? https://github.com/pavelloz/upptime/blob/master/.upptimerc.yml
GH_TAP secret is of course set up, but maybe it needs more access rights (i selected repo, per documentation)?

**Comment by pavelloz** [comment]
Ouh, actually found another error, which is probably responsible for not publishing gh pages:

```
error: src refspec ***@github.com/pavelloz/upptime.git does not match any
error: failed to push some refs to 'https://'
```

But i think it is connected to the previous one - it tried to use https and not ssh, for whatever reason.
I noticed that in my logs some part of the url is censored, and in your log its not - maybe thats a clue.

```
To https://github.com/upptime/upptime.git
 + 20aff7b...850db17 master -> gh-pages (forced update)
Content of site/status-page/__sapper__/export/ has been deployed to GitHub Pages.
```

https://github.com/upptime/upptime/runs/1415644849?check_suite_focus=true#step:5:53

**Comment by AnandChowdhary** [comment]
Quick question, have you added your `GH_PAT`?

**Comment by AnandChowdhary** [comment]
I see in your first comment that you said `GH_TAP` is set up. Can you confirm that you've in fact set up `GH_PAT` (PAT for personal access token, not TAP)?

**Comment by pavelloz** [comment]
Yep, PAT like Patrick :)
<img width="116" alt="image" src="https://user-images.githubusercontent.com/546845/99573525-81104780-29d6-11eb-8711-c82197d78879.png">

I think if secret was the problem readme would not update as well, but that part is working great. Its pinging, updating charts, readme, workflows, etc.

**Comment by pavelloz** [comment]
Ok, i started from scratch, with simplest possible setup and its working. So i think im just going to rename new repo to the name i want and go from that. 
It would be nice to know how i managed to break it but the cryptic github message is too much for my creativity.

Great job on the tool, really fun to use :)

**Comment by AnandChowdhary** [comment]
Okay, if you find out what went wrong, please let me know! 😄

**Comment by pavelloz** [comment]
Sorry i deleted my comment to not be remembered as the laziest person in the world.

Anyway! Important part: Thank you for the tool, great to have a pleasant and fun to use tool for uptime :D

**Comment by pavelloz** [comment]
I look at a lot of weird and different things, but this might be the coolest piece of software ive seen this year. :)

One day i will understand how it works :D

**Comment by jcortell** [comment]
I received the same error. It would be good to know what causes it, as I had not changed anything (to my knowledge) before it started failing. The only thing I can think of is the GH_PAT, but I updated/renewed it twice, so I have no idea what else could it be. Any suggestions?
Also, +1 for coolest software!
