### ISSUE TITLE
Static Site CI Failure: Unable to download Cypress

### ISSUE THREAD

**Issue by frankdejonge** [upptime/upptime#603]
The `Static Site CI` fails due to not being able to download Cypress

See the output here: https://github.com/frankdejonge/uptime-monitors/runs/7131922875?check_suite_focus=true

**Comment by AnandChowdhary** [comment]
Looks like a weird one-off npm error... can you try re-running the workflow?

**Comment by frankdejonge** [comment]
I had run it a couple times (3 or 4) times when I encountered this. I'll check again and report back.

**Comment by frankdejonge** [comment]
This seems to be back up now. Will close this issue.

**Comment by AnandChowdhary** [comment]
Thanks for checking! :)
