### ISSUE TITLE
CSS bug with `<article>`'s nested `<a>` (entire `<article>` should be clickable, not just the `<a>` inside `<h4>`)

### ISSUE THREAD

**Issue by titanism** [upptime/upptime#615]
Right now there is weird mouse-cursor behavior due to CSS block display.

The entire `<article>` should be clickable, but now only a portion of it is.
<img width="758" alt="Screen Shot 2022-07-11 at 1 57 56 PM" src="https://user-images.githubusercontent.com/101466223/178338548-eb342606-60b4-4e7a-898d-348792f2b6d5.png">

<img width="780" alt="Screen Shot 2022-07-11 at 1 58 06 PM" src="https://user-images.githubusercontent.com/101466223/178338558-93f413eb-d104-4c90-8282-ee0999bb6aa1.png">

Using this at https://status.forwardemail.net.  I suppose we could write a custom CSS workaround, but this should be default behavior.

Thanks so much for this @AnandChowdhary 🙇

**Comment by AnandChowdhary** [comment]
Makes sense! We can use the CSS ::after trick to make the entire article clickable. Happy to accept a PR!

**Comment by AnandChowdhary** [comment]
All done!
