### ISSUE TITLE
Error: Unable to find workflow 'Graphs CI' in pavelloz/instances-uptime 😥

### ISSUE THREAD

**Issue by pavelloz** [upptime/upptime#62]
Well, this is weird :)

I just created another instance to monitor another set of pages and for some reason this is what I get on Setup CI workflow:

> Error: Unable to find workflow 'Graphs CI' in pavelloz/instances-uptime 😥

https://github.com/pavelloz/instances-uptime/runs/1421583962?check_suite_focus=true#step:6:6

Im pretty sure i have Graphs CI workflow as I did not touch it
<img width="238" alt="image" src="https://user-images.githubusercontent.com/546845/99606661-77a0d280-2a0a-11eb-9779-30c1d71d5005.png">

I did one mistake but i dont know if it can have any impact: I have run workflow first time before I created GH_PAT, so maybe state somewhere was saved and now order of workflows is not correct.

Anyway - Just like a previous time i will just start from scratch (and it will work!), but i think there is some fragile part of those workflows (my guess is: their communication with each other) that breaks them if something is run in the not optimal order (like missing secret, or missing directories, which i had to create by hand :) )

Those directories are suspicious - Everytime i cleaned them up (leaving empty directory for git means they are not commited), something went wrong. I had to create them by hand, add `.keep` to commit them. Maybe script should detect if there is dir and then try to save to file, instead of throwing error that history/xx.yml is not present etc.

**Comment by pavelloz** [comment]
Quick update: My prediction was right - i did everything slower, with more pushes along the way, and everything works. It looks like scripts just dont like when you change too much at once ;)

**Comment by AnandChowdhary** [comment]
Yes, I agree! I pushed an update last night that ensures that the three required directories, `history`, `api`, graphs` exist before starting the workflows.

**Comment by AnandChowdhary** [comment]
This is super weird, if the workflows are in the right folder (which they are), GitHub should add them as actions. Maybe you can create an empty `.yml` file in the `.github/workflows` folder to see if GitHub will reindex your workflows?

**Comment by pavelloz** [comment]
Heh, i thought it was something new, but apparently this is same old friend:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/546845/99670734-45768b80-2a71-11eb-8028-b029dca387e4.png">

I guess I will follow Jocko advise closer to avoid doing the same work twice: `Slow is smooth, smooth is fast.`

**Comment by AnandChowdhary** [comment]
I think this is fixed now, because we check whether you've updated your `.upptimerc.yml` config file before running any workflows. If you haven't, we do nothing, so hopefully this doesn't happen again. Please feel free to reopen this issue in case this doesn't work for you. 🤞

**Comment by pavelloz** [comment]
Got it :)

**Comment by cwdcwd** [comment]
FWIW I had this same issue with the `Graph CI` workflow and it was because my default branch was not `master` 
I think it may be related to [this issue](https://github.com/benc-uk/workflow-dispatch/issues/13)

**Comment by itsBaivab** [comment]
just add a small comment in the `graphs.yml ` . It will refresh the state of the file where is it stored in github and now your access tokens can communicate with the `Graphs CI` workflow and it should properly work now.
