### ISSUE TITLE
404 when load css

### ISSUE THREAD

**Issue by azl397985856** [upptime/upptime#643]
**Describe the bug**

status website got an 404 error when load css files 

**To Reproduce**
1. Go to https://lucifer.ren/leetcode-pp-available/
2. 404 error when load theme css

> I have configure the base_url in my yml file correctly. so all other files works fine eg: js files.  I also check the index.html which includes `<base href="/leetcode-pp-available/">`

**Expected behavior**

load https://lucifer.ren/leetcode-pp-available/themes/light.css

instead of https://lucifer.ren/themes/light.css

**Screenshots**
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/12479470/187037147-129d9f8e-bd5a-442d-a653-db52b6571849.png">

my repo: https://github.com/azl397985856/leetcode-pp-available

**Comment by AnandChowdhary** [comment]
Can you share your .upptimerc.yml or repository?

**Comment by azl397985856** [comment]
my repo: [azl397985856/leetcode-pp-available](https://github.com/azl397985856/leetcode-pp-available)

**Comment by Fatichti** [comment]
did you reach to find a solution ?

**Comment by AnandChowdhary** [comment]
I see! Turns out subdirectories don't work with custom domain, but this should be a feature we should add!

**Comment by azl397985856** [comment]
@AnandChowdhary thx. looking forward to this feature

**Comment by mkhorton** [comment]
We're having a similar issue here https://materialsproject.github.io/status/, where both CSS and JS are not loading. Could this be related?

**Comment by AnandChowdhary** [comment]
@mkhorton No, you have the "/status" as the base URL missing in https://github.com/materialsproject/status/blob/master/.upptimerc.yml#L31.

**Comment by KiroFyzu** [comment]
i have sasme issue 
![Uploading image.png…]()

**Comment by AnandChowdhary** [comment]
https://github.com/KiroFyzu/upptime/blob/dcd8ad89e49a8d51e9c67d7f5d2b68277b48eecb/.upptimerc.yml#L8

Can you please remove the `|` in the website names? I think it causes issues with markdown tables. Also, could you please check your repository settings to ensure that GitHub Pages is indeed enabled and publishing from the `gh-pages` branch?

**Comment by yarikoptic** [comment]
What about us?
- https://www.dandiarchive.org/upptime/
- https://github.com/dandi/upptime/blob/master/.upptimerc.yml#L54

**Comment by AnandChowdhary** [comment]
@yarikoptic I think this could be the issue that Upptime works either with a custom domain or a /base-url, but not both. I think I've noticed this elsewhere before but haven't had a chance to fix it. :(

**Comment by AnandChowdhary** [comment]
I think adding the base URL to this line should fix the issue: https://github.com/upptime/status-page/blob/9b4cd08f4243c86487a18ad7f4eac813e92c4607/pre-process.ts#L25 Happy to accept a PR!

**Comment by yarikoptic** [comment]
should I just add `/base-url` to `cname` or there are uses of `cname` which really want domain name?

**Comment by yarikoptic** [comment]
> I think adding the base URL to this line should fix the issue: https://github.com/upptime/status-page/blob/9b4cd08f4243c86487a18ad7f4eac813e92c4607/pre-process.ts#L25 Happy to accept a PR!

initial PR was submitted
- https://github.com/upptime/status-page/pull/545
but I do not really know how to try it out.

**Comment by AnandChowdhary** [comment]
Thank you, I appreciate it!

**Comment by AnandChowdhary** [comment]
We just shipped an update and it should probably work now. Can someone please test here by running "Static Site CI" manually and waiting for the updated site to be live, and if it still doesn't work please share the link here and I'll investigate? Thanks @yarikoptic for your contribution!

**Comment by yarikoptic** [comment]
Yay, works now
![Screenshot_20240402-143555](https://github.com/upptime/upptime/assets/39889/ba36c9b5-485a-4482-a1e7-89f17a5b06b4)

**Comment by AnandChowdhary** [comment]
🎉
