### ISSUE TITLE
Status Down - but the sites are up

### ISSUE THREAD

**Issue by OsintUK** [upptime/upptime#680]
Many sites are stating they are down, but they are up!!

Any help on why this could be would very much appreciated

**Comment by AnandChowdhary** [comment]
Do you have a link to your repository or the action logs?

**Comment by OsintUK** [comment]
Sure, I'm currently testing to see if upptime can be useful in monitoring hacking forums as apart of a bigger project.

https://github.com/OsintUK/Up-or-Down

**Comment by OsintUK** [comment]
All current sites showing as offline are online

**Comment by AnandChowdhary** [comment]
It looks like your YAML configuration is invalid. This should be in quotes (""): https://github.com/OsintUK/Up-or-Down/blob/master/.upptimerc.yml#L26
