### ISSUE TITLE
Help me run action Setup CI 

### ISSUE THREAD

**Issue by chatquick** [upptime/upptime#681]
<div class="mt-1 mb-3 px-3">
          <div class="mx-0 mx-md-1">
            <h4 class="text-bold">Annotations</h4>
            <div class="color-fg-muted text-small">1 error and 2 warnings</div>
          </div>
        </div>
        

 
--

                      <a class="d-block no-underline Link--secondary color-fg-default" href="https://github.com/chatquick/status/actions/runs/3551589676/jobs/5965895406#step:2:11">
                          <strong>Setup Upptime</strong>
                        
                      </a>
                      <div class="color-fg-muted">
                        <div data-target="annotation-message.annotationContainer" class="text-small text-mono annotation--contracted">
                          <div>The `save-state` command is deprecated 
and will be disabled soon. Please upgrade to using Environment Files. 
For more information see: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/</div>
                        </div></div>

**Comment by AnandChowdhary** [comment]
Can you share a link to your repository or the workflow logs? The warning doesn't matter for now but the error is unexpected.

**Comment by chatquick** [comment]
> Can you share a link to your repository or the workflow logs? The warning doesn't matter for now but the error is unexpected.
Hi
https://github.com/chatquick/status/actions

**Comment by AnandChowdhary** [comment]
The error reads:

> Error: Input required and not supplied: token

Please follow the getting started guide and add the necessary environment variables: https://upptime.js.org/docs/get-started
