### ISSUE TITLE
"Back to all incidents" link on incident details page always leads to domain root

### ISSUE THREAD

**Issue by querkmachine** [upptime/upptime#69]
Ahoy!

On the deployed GitHub Pages site, the "Back to all incidents" link that appears at the bottom of the incident details page appears to always return to the site root, regardless of the `baseUrl` configuration option. 

For example, the link on https://severnbronies.github.io/status/incident/1 points to https://severnbronies.github.io, when I would expect it to lead to https://severnbronies.github.io/status.

Not sure if related to my previous issues with getting set up (issue #61), but judging by [the line of code responsible](https://github.com/upptime/status-page/blob/45c11e53db461aa59b8e5d345367b0a0e7c8bdc3/src/components/Incident.svelte#L124) it seems like this would happen in any situation where `baseUrl` is used.

**Comment by AnandChowdhary** [comment]
Yep, this needs to be fixed!

**Comment by xoff1337** [comment]
![image example](http://joxi.ru/YmEGJE7SMv3jxA.png) - https://github.com/upptime/upptime/blob/5fa6a6c074247d47455bd5e5c8cd4322b2655ba7/site/src/components/ActiveIncidents.svelte#L75 
edit pls add $REPO mb from yml file settings, idk :D 👍

**Comment by GrahamSH-LLK** [comment]
Yeah, there are a bunch of these glitches. I keep forgetting to report them, so I'm glad someone did. :smile:

**Comment by maximousblk** [comment]
logo on the nav also leads to domain root instead of base url

![image](https://user-images.githubusercontent.com/28438021/99902493-42cf9c80-2ce4-11eb-992e-ac9cb315407c.png)

**Comment by LukePrior** [comment]
This issue is still present on my site, I have set the baseURL:

```
status-website:
  baseUrl: /OpenBankingUptime
```

I have the following navbar entry:

```
navbar:
    - title: Home
      href: /
```

The navbar takes me to https://lukeprior.github.io/ instead of https://lukeprior.github.io/OpenBankingUptime/
