### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by thomasmerz** [upptime/upptime#693]
**Describe the bug**
Running your actions says:  
> Node.js 12 actions are deprecated

For example: https://github.com/thomasmerz/upptime/actions/runs/3687139523

**Expected behavior**
No deprecation warning should appear.

**Screenshots**
>  Check status
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: **actions/checkout@v2.3.3, upptime/uptime-monitor@v1.29.0**

I started fixing it in my repo: https://github.com/thomasmerz/upptime/commit/8172cece3447aa7e19e174bbbfe2fc14570cd379

But it says:
```
# This file was generated by upptime/uptime-monitor@v1.29.0
#
# ===============================
# Do not edit this file directly!
# ===============================
#
# Your changes will be overwritten when the template updates (daily)
# Instead, change your .upptimerc.yml configuration: https://upptime.js.org/docs
```

So I think it should be fixed upstream!?

**Comment by thomasmerz** [comment]
I found this deprectation warnings also "by accident" and not by (re)search… GitHub should make this more transparent in some convenient way…

**Comment by thomasmerz** [comment]
@AnandChowdhary , can you also please review https://github.com/upptime/uptime-monitor/pull/204 ? I'm really no programmer (but a linux-sysadmin) and absolutely not sure if this simple fix is working… 🤷🏼‍♂️

**Comment by AnandChowdhary** [comment]
All done, thank you!

**Comment by thomasmerz** [comment]
Thank you, too 😃
