### ISSUE TITLE
Update Template CI is failing

### ISSUE THREAD

**Issue by thomasmerz** [upptime/upptime#695]
**Describe the bug**
```
Error: The module '/home/runner/work/_actions/upptime/uptime-monitor/master/dist/lib/binding/node_libcurl.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
See https://github.com/thomas-merz/upptime/actions/runs/3709155438/jobs/6287479650 for example and many other users should/might also be affected.

**Expected behavior**
No error should occur.

**Additional context**
I'm not sure which PR is responsible for this:
https://github.com/upptime/uptime-monitor/pull/204 (my PR)
https://github.com/upptime/uptime-monitor/pull/205 (@zgrossbart)

**Comment by AnandChowdhary** [comment]
I fixed this last night in https://github.com/upptime/upptime/issues/694. Can you please manually run Update Template CI and confirm that you're still facing this issue? Thanks!

**Comment by thomasmerz** [comment]
https://github.com/thomasmerz/upptime/actions/runs/3715874827 ✅
