### ISSUE TITLE
bug: Error while running the "Setup CI"

### ISSUE THREAD

**Issue by maximousblk** [upptime/upptime#74]
screenshot:

![image](https://user-images.githubusercontent.com/28438021/99901247-32ff8a80-2cdb-11eb-8c23-50988fe8ee35.png)

to reproduce:
- [Generate](https://github.com/upptime/upptime/generate) a repo using the [`upptime/upptime`](https://github.com/upptime/upptime) template.
- Add `DISCORD_WEBHOOK_URL` and `GH_PAT` secerets
- Update the `.upptimerc.yml` file and push

**Comment by maximousblk** [comment]
Btw I'd recommend not to use `@master` branch of the actions in the template. lock it to a version and update the version when running "Update Template CI".

**Comment by AnandChowdhary** [comment]
Do you have a repo link for me? It seems like it couldn't find the `history/web.yml` history file for some reason, let me quickly check!

**Comment by ball-hayden** [comment]
I'm seeing the same:
https://github.com/ball-hayden/playerdata-status/runs/1438019811?check_suite_focus=true

**Comment by AnandChowdhary** [comment]
This is fixed now. You should see it work again in a few minutes. 😄

**Comment by AnandChowdhary** [comment]
> Btw I'd recommend not to use @master branch of the actions in the template. lock it to a version and update the version when running "Update Template CI".

I agree, I think I'll change the template to use specific versions and update them weekly with the CI. I just wanted to wait until all the "main" features of Upptime are finished, so it's "stable", but I think we're there already. I'll make these changes

**Comment by AnandChowdhary** [comment]
upptime/uptime-monitor is now pinned to v1.16.1 in the template.
