### ISSUE TITLE
bug: uptime 0%

### ISSUE THREAD

**Issue by maximousblk** [upptime/upptime#75]
uptime seems to be always at 0%

![image](https://user-images.githubusercontent.com/28438021/99901800-647a5500-2cdf-11eb-8f6f-17e6bcc58293.png)

![image](https://user-images.githubusercontent.com/28438021/99901815-7f4cc980-2cdf-11eb-9429-3b9e943a6cd6.png)

This started happening today.

**Comment by AnandChowdhary** [comment]
Aah, sorry! This is fixed.

I saw a `-0.00%` because of rounded with "Broken Site" in the demo, so I added a `Math.min` instead of `Math.max`, this is fixed now!
