### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by MomentQYC** [upptime/upptime#752]
relate #704

It turns out that this error occurs whenever "https://raw.githubusercontent.com/" is not accessible in the visitor's region.
```
An error occurred
An error occurred while trying to get the latest status details.

You can try again after a while.
```

The only solution I can think of at the moment is to add a configuration item to allow users to use the GitHub proxy site.

**Comment by AnandChowdhary** [comment]
Yes, we have a configuration to overwrite the default GitHub URL, but since Upptime is heavily tied to GitHub, the best solution is to use a GitHub proxy URL.
