### ISSUE TITLE
Bug: Major bug (initial page load has uncaught exception in client-side JS payload)

### ISSUE THREAD

**Issue by titanism** [upptime/upptime#758]
See these screenshots, this is an issue affecting every status page using upptime:

<img width="1294" alt="Screen Shot 2023-03-30 at 12 00 15 AM" src="https://user-images.githubusercontent.com/101466223/228734228-797e8b0d-ad67-48ba-8dc4-3a3ef460c45d.png">

<img width="613" alt="Screen Shot 2023-03-30 at 12 00 21 AM" src="https://user-images.githubusercontent.com/101466223/228734226-c1cadaaa-abdb-4385-a9c9-fa09c6558370.png">

**Comment by AnandChowdhary** [comment]
I just pushed a fix, can you please try running Static Site CI manually and see if it works for you?

**Comment by woeterman94** [comment]
Same issue here:
![image](https://user-images.githubusercontent.com/5755057/231190791-98b18085-8a7d-46fe-a2d1-bdcdf783db25.png)

**Comment by AnandChowdhary** [comment]
Thank you so much to the best email forwarding service! <3
