### ISSUE TITLE
[Issue] Node.js 12 deprecation warning in all workflow files.

### ISSUE THREAD

**Issue by vp-en** [upptime/upptime#770]
**Describe the bug**
Node.js 12 deprecated in pretty much all workflow files.

Thinking this commit might be the culprit: https://github.com/upptime/uptime-monitor/commit/891496a3ff309d1a898df5519854c1fdaac42d24

The decision to downgrade to v12 happened at a bad time, since Github is [actively deprecating](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12) that exact version. Hopefully Upptime can run on v16 or similiar if v18 was bugged?

**To Reproduce**
1. Go to the [Upptime repo](https://github.com/upptime/upptime)
2. Click on the `Use this template` and mark the `Include all branches`
3. Edit the `.uptimerc.yml` file and let the `setup.yml` workflow do it's thing
4. Wait till the `upptime-bot` upgrades the workflow files to v1.29.0 (latest version of this writing)
5. Notice all workflow files get the same error message in the `Actions` tab on Github:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: upptime/uptime-monitor@v1.29.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

**Expected behavior**
I hope not to see this error, since Github has begun deprecating Node 12 already, [according to the article](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12) they mention in the warning message.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chromium based
 - Version: 

**Additional context**
I don't have screenshots, but here are links and examples of pretty much all workflow files getting the same deprecation notice:
```
graphs.yml: https://github.com/upptime/upptime/blob/master/.github/workflows/graphs.yml
Action Example: https://github.com/upptime/upptime/actions/runs/4781492334
Warning Message: Node.js 12 actions are deprecated. 

response-time.yml: https://github.com/upptime/upptime/blob/master/.github/workflows/response-time.yml
Action Example: https://github.com/upptime/upptime/actions/runs/4780844953
Warning Message: Node.js 12 actions are deprecated. 

setup.yml: https://github.com/upptime/upptime/blob/master/.github/workflows/setup.yml
Action Example: https://github.com/vp-en/upptime/actions/runs/4780030036
Warning Message: Node.js 12 actions are deprecated. 

site.yml: https://github.com/upptime/upptime/blob/master/.github/workflows/site.yml
Action Example: https://github.com/upptime/upptime/actions/runs/4781736905
Warning Message: Node.js 12 actions are deprecated. 

summary.yml: https://github.com/upptime/upptime/blob/master/.github/workflows/summary.yml
Action Example: https://github.com/upptime/upptime/actions/runs/4781397451
Warning Message: Node.js 12 actions are deprecated. 

update-template.yml: https://github.com/upptime/upptime/blob/master/.github/workflows/update-template.yml
Action Example: https://github.com/upptime/upptime/actions/runs/4781514971
Warning Message: Node.js 12 actions are deprecated. 

updates.yml: https://github.com/upptime/upptime/blob/master/.github/workflows/updates.yml
Action Example: https://github.com/upptime/upptime/actions/runs/4782136735
Warning Message: Node.js 12 actions are deprecated. 

uptime.yml: https://github.com/upptime/upptime/blob/master/.github/workflows/uptime.yml
Action Example: https://github.com/upptime/upptime/actions/runs/4790502498
Warning Message: Node.js 12 actions are deprecated. 
```

**Comment by redlinejoes** [comment]
I would also like to help resolve this. There is no information regarding the issue, but this commit is for reverting to Node.js 12. 
https://github.com/upptime/uptime-monitor/commit/5f7f2072c6830b964a034b3ce218d5ae9038e5f3
Unfortunately, there are no details as to why or what happened. 
If more information is provided, the open-source community could assist. 
I have forked the repo and intend to investigate the issue further.

**Comment by AnandChowdhary** [comment]
@redlinejoes In https://github.com/upptime/uptime-monitor/pull/205, Node.js was upgraded to v18 but node-libcurl was not working. Maybe these commits will help you move in the right direction? Thank you for your contributions!

<img width="1248" alt="CleanShot 2023-04-25 at 08 43 29@2x" src="https://user-images.githubusercontent.com/2841780/234195212-48779903-b4df-4433-8498-23a0e1cdbc4f.png">

**Comment by redlinejoes** [comment]
Thank you for pointing these out to me. This does help explain the issue more clearly for me to investigate further.

**Comment by vp-en** [comment]
Fixed in:
https://github.com/upptime/uptime-monitor/pull/214
https://github.com/upptime/uptime-monitor/pull/217
