### ISSUE TITLE
"API rate limit exceeded for installation ID X"

### ISSUE THREAD

**Issue by eltiszl** [upptime/upptime#786]
Hi,

All out of a sudden I started getting a API rate limit exceeded for installation ID X error on every Action.

**Example:**
![API rate limit exceed for installation ID X](https://github.com/upptime/upptime/assets/53695454/3ad1458d-9573-47dc-b0f8-4b75d638f928)

Has anybody else experienced this issue, and if so, how did you fix it?

Thanks :-)

**Comment by AnandChowdhary** [comment]
Do you still see this error?

**Comment by eltiszl** [comment]
I don't! This problem seems to be solved, although I didn't make any changes.
