### ISSUE TITLE
Duplicate percentage on the status page

### ISSUE THREAD

**Issue by Taku-Yamashita** [upptime/upptime#79]
Hello !  Thank you for awesome this project.
I currently use uptime/uptime-monitor(2c02d16) and I found duplicate percentage string on the status page.

This seems to be due to the presence of duplicate % on the template side and the data side.

![スクリーンショット 2020-11-23 17 05 01](https://user-images.githubusercontent.com/27942145/99940571-be4a5000-2daf-11eb-8c9e-5b2c067baf62.png)

**Comment by AnandChowdhary** [comment]
This is fixed in https://github.com/upptime/status-page/pull/64 😄
