### ISSUE TITLE
Error while running Update Template CI (workflow scope required in PAT)

### ISSUE THREAD

**Issue by richardtape** [upptime/upptime#81]
Hi,

I really like the idea behind this and have been running it for a couple days; thanks so much for putting this together. Over the weekend, one of the CI Actions failed:

https://github.com/richardtape/ubcupptime/runs/1443340141?check_suite_focus=true

In order to fix this I needed to issue a new PAT with both the repo AND workflow scopes (hinted at in the error linked above). May need a quick tweak to the docs, unless I have something wrong? If I'm being honest I don't recall there being a separate workflow scope when I first set this up, so maybe that's a new thing?

Happy to make a PR for the docs if the above is what is needed,

Rich

**Comment by AnandChowdhary** [comment]
Yes, it seems like we now need the `workflow` scope for this to work. Hmm, I also don't recall that.

Can you make a PR to the docs repository?

**Comment by AnandChowdhary** [comment]
I'm creating as automated issue in each public Upptime repository, asking people to add the `workflow` scope to their personal access tokens. Thanks for bring this up, @richardtape!

**Comment by richardtape** [comment]
My pleasure and thanks so much for being responsive so quickly to this little hiccup.

**Comment by pavelloz** [comment]
That auto issue thing is great! Thanks :)
