### ISSUE TITLE
Unable to customize favicon

### ISSUE THREAD

**Issue by mrspence** [upptime/upptime#813]
> Just to say... this is an Open Source project I really admire; thank you so much for your time in building, releasing, and open sourcing this project.

**Describe the bug**
Currently the favicon of any status page cannot be changed and defaults to:

![image](https://github.com/upptime/upptime/assets/30320791/344bce98-4573-4893-bd21-7c949f88afee)

**Expected behaviour / proposed solution**
A `public` or `static` folder option to deploy files that overwrite default files. In here you could place a `favicon.ico` file that overwrites the default.

**Comment by josecsotomorales** [comment]
👍🏻

**Comment by AnandChowdhary** [comment]
Have you tried this? https://upptime.js.org/docs/configuration/#custom-favicons

Or is the use case more general-purpose? I think we need to document this better, but AFAIK the `assets` directory will serve static files: https://upptime.js.org/docs/configuration/#theme
