### ISSUE TITLE
getting error when putting base url

### ISSUE THREAD

**Issue by Prasungoyal23** [upptime/upptime#831]
I have attached screenshot of error 

[](url)
![Screenshot 2023-08-10 203149](https://github.com/upptime/upptime/assets/141539749/802fac3e-5da0-43d0-826e-ee5898e35c37)
![Screenshot 2023-08-10 203115](https://github.com/upptime/upptime/assets/141539749/d34d0158-f1d4-4f5d-9c91-d49ce801f88a)

**Comment by AnandChowdhary** [comment]
There's a loose space " " between "baseUrl"; you can see the error "bad indentation"
