### ISSUE TITLE
CSS not loading after adding baseurl

### ISSUE THREAD

**Issue by Prasungoyal23** [upptime/upptime#832]
https://prasungoyal23.github.io/status/

**Comment by AnandChowdhary** [comment]
This looks like the default GitHub README and not the GitHub Pages website. Can you please confirm that you have set up GitHub Pages correctly and share a screenshot of the GitHub Pages settings UI?

**Comment by AnandChowdhary** [comment]
Also looks like your username in this line is incorrect, which is why the README is not correctly generated: https://github.com/Prasungoyal23/status/blob/256fbee3405fc3c945c382c66888f87542c2c577/.upptimerc.yml#L2

**Comment by Prasungoyal23** [comment]
dear sir I am attaching SC please go threw 
![Screenshot 2023-08-11 145435](https://github.com/upptime/upptime/assets/141539749/9c436f91-5828-415e-82eb-397e7db982e8)
