### ISSUE TITLE
Wrong duration of down-time

### ISSUE THREAD

**Issue by retog** [upptime/upptime#838]
**Describe the bug**
A service with frequent short down-times gets notes stating much longer downtimes than it actually had^.

**To Reproduce**
1. Go to 'https://plazi.github.io/monitoring/incident/13'
2. Compare the 'Opened at' and 'Closed at' times
3. Scroll down to 'Resolved'
4. See that even though the issue was closed 21 minutes after being opened, it says that the service is backup after more than 13 days.

**Expected behavior**
Read that the service is back up after 21 minutes

**Screenshots**
![image](https://github.com/upptime/upptime/assets/110756/b4e92c4f-dbc7-4017-8800-e76e8005344b)

**Additional context**
The summary page shows the expected durations:
![image](https://github.com/upptime/upptime/assets/110756/d9f6b5f4-1133-4452-ba39-64149971a53e)

**Comment by AnandChowdhary** [comment]
You're right, this bug resulted in https://github.com/upptime/uptime-monitor/pull/222 and I'm fixing it now!
