### ISSUE TITLE
Wrong time shown on website back up!

### ISSUE THREAD

**Issue by Zaid-maker** [upptime/upptime#841]
**Describe the bug**
Wrong time shown on website backup

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/upptime/upptime/assets/53424436/4d6b5a9b-e91c-4285-b1ff-802f9873d13b)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AnandChowdhary** [comment]
You're right, I just pushed a fix earlier today: https://github.com/upptime/uptime-monitor/releases/tag/v1.31.2

I'll keep this issue open until next week for visibility!

**Comment by Zaid-maker** [comment]
> You're right, I just pushed a fix earlier today: https://github.com/upptime/uptime-monitor/releases/tag/v1.31.2
> 
> I'll keep this issue open until next week for visibility!

Sure i check the commit i will also double check it

**Comment by Zaid-maker** [comment]
The issue is fixed it's now showing correct time on website back up
