### ISSUE TITLE
I want to ask

### ISSUE THREAD

**Issue by Julius-Ulee** [upptime/upptime#847]
Why doesn't it perform and it's also messy, did I setup it wrong?

![image](https://github.com/upptime/upptime/assets/61336116/c10b64d1-8455-49e6-82c5-9cf92074e6b3)

**Comment by AnandChowdhary** [comment]
Yes, probably something incorrect in your configuration. Can you please share your `.upptime.yml`?

**Comment by Julius-Ulee** [comment]
> Yes, probably something incorrect in your configuration. Can you please share your `.upptime.yml`?

oh of course 

[link](https://github.com/Julius-Ulee/Status/blob/master/.upptimerc.yml)

**Comment by AnandChowdhary** [comment]
You need to add your repository name here: https://github.com/Julius-Ulee/Status/blob/6828db3ed7f6537546cc08a112093dc0d3ff641a/.upptimerc.yml#L29

Please enter:

```yaml
baseUrl: /Status
```
