### ISSUE TITLE
Problem on the link on github pages

### ISSUE THREAD

**Issue by SJang1** [upptime/upptime#85]
![image](https://user-images.githubusercontent.com/29011440/100052728-d8dd0180-2e61-11eb-93f3-6d8fc37e0abe.png)

there is two slashes(//) in the link, and page desn't load correctly.
It there is only one slash(/) it loads correctly, but page look like it has two of it. 
https://$username.github.io/#repo//history/$name needs to be corrected to : https://$username.github.io/#repo/history/$name

**Comment by AnandChowdhary** [comment]
This is now fixed. 😄
