### ISSUE TITLE
websites with down status but they are up and running

### ISSUE THREAD

**Issue by 7zx** [upptime/upptime#867]
**Describe the bug**
My websites are all with the status "down", but they are all up and running.

**To Reproduce**
1. Go to [status.polido.pt](https://status.polido.pt/)

**Expected behavior**
They should be all with the "up" status.

**Comment by 7zx** [comment]
my repo: https://github.com/7zx/status.polido.pt

**Comment by AnandChowdhary** [comment]
I think it's probably just random fluctuations, sometimes the request fails and the site is marked as down, but when this happens and the next request is up, we undo that and mark it as up again, so please let me know if this is still an ongoing problem, and I'll reopen this issue!
