### ISSUE TITLE
Please use [actions/checkout] Release v4

### ISSUE THREAD

**Issue by thomasmerz** [upptime/upptime#871]
There has been a major update for [actions/checkout](https://github.com/actions/checkout/releases/tag/v4.0.0).

So please use v4 instead of old v3.

**Comment by AnandChowdhary** [comment]
@EmnichtdaYT I'm going to close this for now since this is not a bug.

**Comment by thomasmerz** [comment]
@AnandChowdhary , here's my PR with the update.

**Comment by AnandChowdhary** [comment]
@thomasmerz This needs to be updated in the file where we programmatically create workflows in the repository upptime/uptime-monitor.

**Comment by thomasmerz** [comment]
@AnandChowdhary - https://github.com/upptime/uptime-monitor/pull/238 should be the right repo / PR!?
