### ISSUE TITLE
False down report on ipv4 tcp-ping

### ISSUE THREAD

**Issue by SetCr4** [upptime/upptime#895]
**Description**
False down report on ipv4 tcp-ping
Below is a part of the Action log.
```
2023-12-14T02:16:56.1664336Z Checking 89.58.57.232
2023-12-14T02:16:56.1702316Z Current status main-server down 2023-06-01T23:15:18.000Z
2023-12-14T02:16:56.1704665Z Using tcp-ping instead of curl
2023-12-14T02:16:56.2540081Z ERROR Got pinging error Error: queryA ENOTFOUND 89.58.57.232
2023-12-14T02:16:56.2542043Z     at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:240:17) {
2023-12-14T02:16:56.2543431Z   errno: undefined,
2023-12-14T02:16:56.2544679Z   code: 'ENOTFOUND',
2023-12-14T02:16:56.2545431Z   syscall: 'queryA',
2023-12-14T02:16:56.2546109Z   hostname: '89.58.57.232'
2023-12-14T02:16:56.2546868Z }
```

**To Reproduce**
Monitor an endpoint using tcp-ping and ipv4.
This does not happen when using an actual url so that `dns.promises.resolve4(url)` has to run.

**Additional context**
My Upptime Instance is public. You can check it out to see the current config.

I'm no expert but I suspect that the check `isIP(url)` (https://github.com/upptime/uptime-monitor/blob/cf6ed7bbc149a58e9d1146a975f43b07d326576e/src/update.ts#L160) may always return false, in which case even an ipv4 would be fed into `dns.resolve4(...)` which would obviously lead to a lookup error.
I just can't explain why `isIP(...)` should fail, unless `url` isn't provided correctly.

**Comment by Trainax** [comment]
I'm encountering the same issue. The server is online however `tcp-ping` reports it as offline

[Link to my instance repo](https://github.com/CyberLions-Italian-Community/status)

**Comment by AnandChowdhary** [comment]
We just pushed an update, hopefully this should fix it!

**Comment by Trainax** [comment]
Updating Upptime to v1.34.1 solved the issue. Thanks!

Do you know if there is any way to make this not count towards the uptime percentage on the status webpage? Thanks again

**Comment by SetCr4** [comment]
Can confirm that 1.34.1 fixed that issue.
Thx for the quick fix :)

**Comment by AnandChowdhary** [comment]
> Do you know if there is any way to make this not count towards the uptime percentage on the status webpage?

I think the easiest would be to manually [delete the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue).

**Comment by Trainax** [comment]
> I think the easiest would be to manually [delete the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue).

Thank you for your reply.

Deleting the issues does remove them from the past incidents on the [status web page](https://status.cyberlions-ita.eu/), however the uptime percentage is still impacted (it should be 100%). Any way to fix that? Thanks again

![immagine](https://github.com/upptime/upptime/assets/30187360/8e303363-74a4-4d09-93b1-64559f2a03fd)

**Comment by AnandChowdhary** [comment]
Hmm you're right. Since it's in the git commit history, I can't think of any easy way to fix the uptime number except for deleting the `.yml` files, adding the `slug` property for the sites so that new, renamed `.yml` files are created, and running "Update CI" manually, which will restart the commit history from the beginning. I know this is not great :(
