### ISSUE TITLE
Release 1.34.2 reports ../assets does not exist when running Static Site CI

### ISSUE THREAD

**Issue by rouilj** [upptime/upptime#900]
**Describe the bug**
After the update to 1.34.2 Static Site CI fails with

```
> Finished in 13.1s. Type npx serve __sapper__/export to run the app.
ERROR Error: cp: no such file or directory: ../assets/*
    at Object.error (/home/runner/work/_actions/upptime/uptime-monitor/v1.34.2/webpack:/@upptime/uptime-monitor/node_modules/shelljs/src/common.js:110:1)
    at /home/runner/work/_actions/upptime/uptime-monitor/v1.34.2/webpack:/@upptime/uptime-monitor/node_modules/shelljs/src/cp.js:246:1
    at Array.forEach (<anonymous>)
    at Object._cp (/home/runner/work/_actions/upptime/uptime-monitor/v1.34.2/webpack:/@upptime/uptime-monitor/node_modules/shelljs/src/cp.js:243:1)
    at Object.cp (/home/runner/work/_actions/upptime/uptime-monitor/v1.34.2/webpack:/@upptime/uptime-monitor/node_modules/shelljs/src/common.js:384:1)
    at Object.generateSite (/home/runner/work/_actions/upptime/uptime-monitor/v1.34.2/webpack:/@upptime/uptime-monitor/dist/site.js:43:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: cp: no such file or directory: ../assets/*
##[debug]Node Action run completed with exit code 1
```

**To Reproduce**
GitHub CI is just running the workflow.: .github/workflows/site.yml

See: https://github.com/rouilj/RoundupAssets/blob/master/.github/workflows/site.yml 

**Expected behavior**
I do not expect to see an error.

**Additional context**

Run log with debugging:

https://github.com/rouilj/RoundupAssets/actions/runs/7242636553/job/19729598752

**Comment by AnandChowdhary** [comment]
Thanks for the report, I fixed this in https://github.com/upptime/uptime-monitor/releases/tag/v1.34.2 but it might take a few days for it to be updated in your workflows, so in the meantime you can run "Update Template CI" manually to fix it immediately.

**Comment by rouilj** [comment]
According to the comment at the top of site.yml I am at 1.34.2:
```
# This file was generated by upptime/uptime-monitor@v1.34.2
```

I have run The "Update Template CI" (https://github.com/rouilj/RoundupAssets/actions/runs/7248399807)
and am rerunning the "Static Site CI" and it still fails as of 1 minute ago:
https://github.com/rouilj/RoundupAssets/actions/runs/7248408716

Any idea what's missing in my setup?

**Comment by AnandChowdhary** [comment]
Yeah I'm sorry, that's totally my bad, the version always shows the latest version 😂. Can you please try running "Update Template CI" manually and when it's done run "Static Site CI" and tell me if you still see an error? Thanks for the report!

**Comment by rouilj** [comment]
Nope still failing.

Successful Update Template CI run: https://github.com/rouilj/RoundupAssets/actions/runs/7254300492
(which doesn't look like it changed anything)

Static Site CI run (with debugging): https://github.com/rouilj/RoundupAssets/actions/runs/7254311032/job/19762894110

**Comment by AnandChowdhary** [comment]
One last try! I pushed a fix that should hopefully do this for us :)

**Comment by rouilj** [comment]
Looks like that last fix works. I have a green "Static Site CI" and "Update Template CI" brought me to 1.35.

Thanks.
