### ISSUE TITLE
Issues are DELETED instead of being CLOSED

### ISSUE THREAD

**Issue by anxolin** [upptime/upptime#917]
**Describe the bug**
When issues are resolved, they are automatically DELETED instead of CLOSED. 

The documentation clearly says they will be closed. In fact, it used to be like that until October 2023. 

**To Reproduce**
This issue looked like this when we had a downtime:

![image](https://github.com/upptime/upptime/assets/2352112/2b792fdc-ba74-4099-863b-7ffd39b90481)

When it was resolved, it just deleted the issue.
![image](https://github.com/upptime/upptime/assets/2352112/a804cc0e-4bc9-4fcd-9790-4451505fc4ee)

See:
https://github.com/cowprotocol/uptime/issues/54

**Expected behavior**
Close the issue instead

**Screenshots**
Already shared above

**Comment by AnandChowdhary** [comment]
Please see https://github.com/upptime/upptime/discussions/492. Let's discuss it there! :)

**Comment by AnandChowdhary** [comment]
Thanks, and sorry for the trouble, if you have a moment please feel free to make a PR in upptime/upptime.js.org and add some docs explaining this functionality :)

**Comment by anxolin** [comment]
@AnandChowdhary here https://github.com/upptime/upptime.js.org/pull/50
