### ISSUE TITLE
Error: Unable to resolve action `fscarmen/warp-on-actions@v2`, unable to find version `v2`

### ISSUE THREAD

**Issue by jiriks74** [upptime/upptime#918]
**Describe the bug**
I've just setup my `upptime` repo again (the workflows weren't running) so I backed it up and created it again. RN the `Setup Upptime` workflow fails with
```
Error: Unable to resolve action `fscarmen/warp-on-actions@v2`, unable to find version `v2`
```

**To Reproduce**
1. Create a new repo from the template
2. Check that GH pages are setup
3. Create the GH token and put it into the `GH_PAT` secret
4. Setup your `.upptime.yml`
5. Go to Actions
6. Open the `Setup Upptime` workflow
7. See the error in logs

**Expected behavior**
`Setup Upptime` workflow successfully running

**Comment by AnandChowdhary** [comment]
We got this from https://github.com/actions/runner-images/issues/668.

@titanism, perhaps it should be v1 instead of v2?

**Comment by jiriks74** [comment]
> We got this from [actions/runner-images#668](https://github.com/actions/runner-images/issues/668).
> 
> @titanism, perhaps it should be v1 instead of v2?

Not really. I've modified the files where it's present and I get this:

```
Error: Unable to resolve action `fscarmen/warp-on-actions@v1`, unable to find version `v1`
```

**Comment by jiriks74** [comment]
@titanism 
I think I fixed it. I looked at the repo and the version that is available is `v1.0`.

From the repo:

> Usage:
>
>   client warp+doh mode
> ```
>  - uses: fscarmen/warp-on-actions@v1.0
>    with:
>      mode: client  # Optional, default
> ```
>    wireguard
> ```
>  - uses: fscarmen/warp-on-actions@v1.0
>    with:
>      mode: wireguard
> ```

In [Releases](https://github.com/fscarmen/warp-on-actions/releases) there's only the `v1.0`.

RN. I've tried this and it works for me as of now.

PS: Since it works now I can go and figure out why the jobs are running avery +- 15 minutes instead of 5 (and sometimes 30m or even hours). Hopefully I've fixed it by modifying the files but we'll see. I've just found this project few days ago so I'm still figuring stuff out.

**Comment by AnandChowdhary** [comment]
Thank you for the fix, I'll make sure this goes live ASAP!

> Since it works now I can go and figure out why the jobs are running avery +- 15 minutes instead of 5 (and sometimes 30m or even hours)

This is documented here: https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working

**Comment by AnandChowdhary** [comment]
I've just shipped this, can you please test this by manually running "Update Template CI" and then running "Setup CI" after the template has been updated? Thanks!

**Comment by jiriks74** [comment]
It's still failing with the same issue @AnandChowdhary

**Comment by jiriks74** [comment]
I can see that [the `v2` is still present in the files instead of `v1.0`](https://github.com/upptime/upptime/blob/8daad4af25029465506c8e42c94c395751d29dd6/.github/workflows/setup.yml#L42-L43)

**Comment by jiriks74** [comment]
I recreated the repo since I broke something and I got the upptime/upptime README instead of mine. I modified the `setup.yml` to use `v1.0` and after running the `warp-on-actions` completely disappeared from all files. Is this what was supposed to happen?

**Comment by jiriks74** [comment]
(I also noticed that response time is ran at 11pm instead of every 6 hours)
https://github.com/upptime/upptime/blob/8daad4af25029465506c8e42c94c395751d29dd6/.github/workflows/response-time.yml#L20-L21

**Comment by AnandChowdhary** [comment]
As you can see from the commit https://github.com/upptime/upptime/commit/c1a25aff868599938bcbbdd5a4fdcc6bad38c7b9, the expected output is that fscarmen/warp-on-actions will be completed removed and instead we've hardcoded the step "Install WARP to support IPv6".

**Comment by AnandChowdhary** [comment]
I'll reopen this issue until we have verification that it works! ✅

**Comment by AnandChowdhary** [comment]
@jiriks74 This new "Install WARP to support IPv6" step is only added for workflows that have an `ipv6: true` site, since your Upptime repository (https://github.com/jiriks74/upptime/commit/f2ae9ae9801df7c0304860fc02e343693d684493) does not have that, this step is unnecessary. Same as yours, @titanism, if you add a site with IPv6 now, I think it should work :)

**Comment by Iliya5digital** [comment]
Where paste token into GH_PAT secret? Which file? Show me the path.

**Comment by AnandChowdhary** [comment]
You're right :( Would you like to make a PR with what's correct? This is where we have to change it - https://github.com/upptime/uptime-monitor/blob/3e32e513ff5d36837223efb82957b67ee5768f42/src/helpers/workflows.ts#L43

**Comment by Iliya5digital** [comment]
friends!
check with me what's wrong https://github.com/Iliya5digital/sites

error Unable to resolve action `fscarmen/warp-on-actions@v2`, unable to find version `v2`

**Comment by AnandChowdhary** [comment]
Added globally!

**Comment by AnandChowdhary** [comment]
Thanks for all your help @titanism, looks like IPv6 is working after adding this - https://github.com/upptime/upptime/commit/b560b6f19f04718506437c8ef3abe9350b3101fa

**Comment by ivancarlos-me** [comment]
It do not work because should use fscarmen/warp-on-actions@v1.1 :/
