### ISSUE TITLE
[setup.yml] [response-time.yml] Yaml syntax error on line: `You can choose client or wireguard.`

### ISSUE THREAD

**Issue by 42Willow** [upptime/upptime#922]
Errors:
1. `Invalid workflow file: You have an error in your yaml syntax on line 77`
https://github.com/upptime/upptime/blob/0a984cdfc1276d5d7a3e4003584a79f165969425/.github/workflows/setup.yml#L77
> [Initial commit action for setup.yml](https://github.com/42Willow/upptime/actions/runs/7636213276)

2. `Invalid workflow file: You have an error in your yaml syntax on line 70`
https://github.com/upptime/upptime/blob/0a984cdfc1276d5d7a3e4003584a79f165969425/.github/workflows/response-time.yml#L70
> [Initial commit action for response-time.yml](https://github.com/42Willow/upptime/actions/runs/7636213220)

**Comment by andrewgioia** [comment]
I'm seeing this same error on a brand deployment of this earlier this morning.

**Comment by patstha** [comment]
Yes, this is in a newline 

https://github.com/upptime/upptime/blob/0a984cdfc1276d5d7a3e4003584a79f165969425/.github/workflows/setup.yml#L77

- name: Install WARP to support IPv6
introduced in a recent change 
https://github.com/upptime/upptime/commit/c1a25aff868599938bcbbdd5a4fdcc6bad38c7b9

**Comment by shellscape** [comment]
@AnandChowdhary can we get a fix for this? this is a catastrophic bug as it prevents setup.

**Comment by AnandChowdhary** [comment]
I just shipped a fix! :) Can you please run "Update Template CI" and once it's updated try running "Setup CI" and see if it works for you?
