### ISSUE TITLE
Overall uptime displays two percentage characters

### ISSUE THREAD

**Issue by idleberg** [upptime/upptime#93]
On the summary page, the percent value is printed with two %-characters. Would have loved to submit a PR, but this is hard to track down

![Screenshot 2020-11-27 at 10 42 18](https://user-images.githubusercontent.com/1504938/100434750-4163f280-309d-11eb-9539-ee939758efb0.png)

**Comment by AnandChowdhary** [comment]
Duplicate of https://github.com/upptime/upptime/issues/92

**Comment by almaashy-99** [comment]
Mohammed
