### ISSUE TITLE
Actions workflows seem to fail due to invalid cron value

### ISSUE THREAD

**Issue by Oj18** [upptime/upptime#94]
Just set it up and I am pretty sure it is all configured well.

Eg: https://github.com/GooseMod/status/actions/runs/388990685

Failed both with and without specific scheduling variables in the configuration, may be a bug from #71? Not sure.

Thanks!

**Comment by AnandChowdhary** [comment]
Aah, damn, this is my fault!

**Comment by Oj18** [comment]
Haha no worries, mainly just wanted to make sure it wasn't me who misconfigured / set it up wrong.

**Comment by AnandChowdhary** [comment]
I've removed the RegExp replacing so this should be fixed when you update your template again (twice, since it'll first update the version of `upptime/uptime-monitor` the first time you run "Update Template CI", and then the second time when it actually updates it). 😄

**Comment by Oj18** [comment]
Cool, I'll try now. Thanks!

**Comment by Oj18** [comment]
(Had an issue with generating the template (something about an "api" dir being missing with scandir) so just going to remake the repo with the template.)

**Comment by AnandChowdhary** [comment]
Yes, that's the easiest, but maybe wait a few mins before creating a new repo? I'm pushing some fixes which should make this A-OK! 😄

**Comment by Oj18** [comment]
Well I did it anyway before you said and had no errors so looks good so haha.
