### ISSUE TITLE
Site always redirects to rate limit page due to 404 GitHub API error (?)

### ISSUE THREAD

**Issue by Oj18** [upptime/upptime#95]
It might be because an API request it tries results in a 404?
![image](https://user-images.githubusercontent.com/19228318/100538176-fa553900-3225-11eb-99f6-9d505a7d4ef0.png)

**Comment by AnandChowdhary** [comment]
This has been fixed already 😄

You can run "Response Time CI" manually and it should be fixed for you. Otherwise it'll automatically run within 24 hours!

**Comment by AnandChowdhary** [comment]
Sorry, I meant you should manually run "Summary CI"

**Comment by Oj18** [comment]
Sorry I was busy. That solved it, thanks.
