### ISSUE TITLE
wrong/old node.js version used

### ISSUE THREAD

**Issue by appdesign1987** [upptime/upptime#969]
the github workflow at https://github.com/upptime/uptime-monitor is using an old node.js version. Node.js 16 instead of node.js 20.
That's causing al other workflows to fail as you can see in the screenshot.

Kindly asking to update the workflow so i can use the upptime monitor again.

![Screenshot 2024-06-04 102719](https://github.com/upptime/upptime/assets/6537807/122e5edc-a434-4bd4-91a4-f450b209d4b7)

**Comment by goldyfruit** [comment]
I'm facing the same issue.

**Comment by mchelen** [comment]
Same here, @goldyfruit what happened in https://github.com/upptime/uptime-monitor/pull/251 ?

**Comment by AnandChowdhary** [comment]
Thank you, this should be fixed!
