### ISSUE TITLE
Telegram notifications dont work with secret sites

### ISSUE THREAD

**Issue by RafGamer** [upptime/upptime#97]
The Telegram notification fails with the HTTP code 400 if a secret site is set up.

I checked the logs and it says:
`"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 25"`.
Then I tried it again with a non-secret URL and it worked.

It seems like Telegram tries to parse the `$` prefix of the environment variables and the `_` in `SECRET_SITE` because of markdown enabled and it fails.

**Comment by AnandChowdhary** [comment]
Aah, very interesting! I'll make sure that it gets the "real" URL since notifications should be allowed to have sensitive info.

**Comment by AnandChowdhary** [comment]
This is fixed!

**Comment by RafGamer** [comment]
Thanks for fixing this so quickly.
