### ISSUE TITLE
Date format in i18n configuration

### ISSUE THREAD

**Issue by olibrian** [upptime/upptime#972]
The date format in the GUI should be displayed depending on the region/country. The DD/MM/YYYY format is currently used. Depending on the locale, a different format (e.g. DD.MM.YYYY) is expected. The desired format (locale) should be defined in the settings.

--

Unfortunately this is currently not supported, but I'd love to accept a PR to add this feature. Here's how I'll go about it:

- Add a new key in the configuration for date/time format
- Use this key to localize .toLocaleDateString() in upptime/status-page

_Originally posted by @AnandChowdhary in https://github.com/upptime/upptime/discussions/486#discussioncomment-4465660_

**Comment by AnandChowdhary** [comment]
Thank you!
