### ISSUE TITLE
Error: fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by vasilvestre** [upptime/upptime#978]
**Describe the bug**
All CI fails suddenly without any modification.

**To Reproduce**
Reproducer here : https://github.com/vasilvestre/status

**Expected behavior**
CI should work as before, the configuration hasn't changed.

**Comment by AnandChowdhary** [comment]
This is happened in the past (https://github.com/upptime/upptime/issues/59). Maybe it's related to https://github.com/actions/checkout/issues/664? Do you remember if you changed your personal access token, MFA, password, etc., recently?

**Comment by vasilvestre** [comment]
The token simply expired after 90 days. Thank you for your help !

**Comment by javdl** [comment]
Same here, token expired and you get this obscure error message.
