### ISSUE TITLE
Cant run the action

### ISSUE THREAD

**Issue by MuntasirSZN** [upptime/upptime#998]
**Describe the bug**
Cant run the setup, stoping always. Gave approapriate perms.

**To Reproduce**
just
1. edit the yaml file.

**Expected behavior**
No errors.

**Screenshots**
![image](https://github.com/user-attachments/assets/8e4480e9-e77f-45ff-97ed-43d39881f77a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.119

Repo: [repo](https://github.com/MuntasirSZN/upptime-monitoring)

**Comment by Jvascs** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by MelanX** [comment]
Your workflow does not have the correct permissions:
```
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
  Packages: read
```

Read the docs for more information: https://upptime.js.org/docs/get-started/#add-repository-secrets

**Comment by MuntasirSZN** [comment]
> Your workflow does not have the correct permissions:
> 
> ```
> GITHUB_TOKEN Permissions
>   Contents: read
>   Metadata: read
>   Packages: read
> ```
> 
> Read the docs for more information: https://upptime.js.org/docs/get-started/#add-repository-secrets

Gave, still.

**Comment by MuntasirSZN** [comment]
And metaDATA is read only by default

**Comment by MelanX** [comment]
It’s still the same permission in your last failed workflow ~13min ago.

**Comment by MuntasirSZN** [comment]
> It’s still the same permission in your last failed workflow ~13min ago.

Sorry, found my problem. The github pat is only accessing my website repo, i accidentally didnt give it access to upptime repo. Sorry for disrurbong. I am turning off the issue.
